#!/usr/bin/env bash
# GLUON_EXAMPLE.sh — end-to-end demo of the stubgen → protoc pipeline that
# populates gluon/. Idempotent: re-running regenerates everything from the
# CSVs under docs/git-links/ without touching the hand-written code.
#
# Pipeline (mirrors README.md's "TODO: per-category gRPC services" intent):
#
#   1. docs/git-links/*.csv         — one CSV per section of git-scm.com/docs/git
#        │                            (produced by `go run ./docs/pull`)
#        ▼
#   2. cmd/stubgen                  — reads CSVs, filters to git-*[1] entries,
#        │                            emits gluon/<pkg>/<pkg>.proto
#        ▼
#   3. gluon/<pkg>/<pkg>.proto      — one gRPC service per section, each RPC
#        │                            taking subcommands.SubCommandReq and
#        │                            returning repo.RepoMsg (shape already
#        │                            used by subcommands/ runner)
#        ▼
#   4. protoc                       — compiles each proto into its own
#                                     gluon/<pkg>/pb/ Go package, referencing
#                                     genpb.SubCommandReq / genpb.RepoMsg via
#                                     module-path imports
#
# Why not invoke gluon directly: accretional/gluon v1's codegen emits
# self-contained protos (types inlined, no import directives), so it would
# duplicate SubCommandReq/RepoMsg nine times. accretional/gluon v2 is an
# EBNF-to-FileDescriptorProto pipeline (orthogonal). accretional/proto-expr
# is a scripting runtime for chaining RPCs (also orthogonal). stubgen mimics
# gluon's naming conventions (snake-case stems, CamelCase RPC names) but
# emits external proto imports, which is the gap for this task.
#
# Usage:
#   ./GLUON_EXAMPLE.sh          # regenerate + compile, commit-ready output
#   ./GLUON_EXAMPLE.sh --check  # regenerate into a tempdir and diff — CI hook
#
# Outputs on success:
#   gluon/<pkg>/<pkg>.proto     committed (source of truth for each service)
#   gluon/<pkg>/pb/*.pb.go      transient; not committed, gitignored
#
# TODO (not done here, deferred until the user wants to move forward):
#   - Extend build.sh to protoc-compile gluon/*/*.proto alongside the root
#     protos so the generated pb/ dirs land in a predictable place.
#   - Export subcommands.Run / RunMkdir so per-command delegator stubs can
#     be generated by a second stubgen pass.
#   - Register each service in cmd/importerd/main.go.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

check_mode=false
if [[ "${1:-}" == "--check" ]]; then
  check_mode=true
fi

./setup.sh >/dev/null

# Step 1 — stubgen: CSV → .proto.
echo "stubgen: regenerating gluon/*/*.proto from docs/git-links/*.csv"
if $check_mode; then
  tmp_proto_root=$(mktemp -d)
  trap 'rm -rf "$tmp_proto_root"' EXIT
  go run ./cmd/stubgen --out "$tmp_proto_root"
  if ! diff -rq gluon "$tmp_proto_root" \
      --exclude=pb --exclude=README.md >/dev/null; then
    echo "gluon/ is out of date — run ./GLUON_EXAMPLE.sh to refresh" >&2
    diff -rq gluon "$tmp_proto_root" --exclude=pb --exclude=README.md >&2 || true
    exit 1
  fi
  echo "gluon/*.proto matches stubgen output."
else
  go run ./cmd/stubgen
fi

# Step 2 — protoc: compile each .proto into gluon/<pkg>/pb/.
# -I . resolves the root-level repo.proto / subcommands.proto imports.
# --go_opt=module= strips the module prefix so outputs land under the gluon/
# tree rather than a mirrored github.com/... scaffold.
echo "protoc: compiling gluon/*/*.proto → gluon/*/pb/"
proto_files=(gluon/*/*.proto)
protoc \
  -I . \
  --go_out=. --go_opt=module=github.com/accretional/proto-repo \
  --go-grpc_out=. --go-grpc_opt=module=github.com/accretional/proto-repo \
  "${proto_files[@]}"

# Step 3 — compile the generated Go packages as a smoke test. Each gluon/<pkg>/pb/
# package references genpb via module-path import, so `go build ./gluon/...`
# exercises the full graph.
echo "go build: verifying generated packages compile"
go build ./gluon/...

# Per-service RPC counts, echoed so a reader can eyeball scale.
echo
printf "generated:\n"
for proto in "${proto_files[@]}"; do
  rpc_count=$(grep -c '^  rpc ' "$proto" || true)
  printf "  %-42s %2d rpcs\n" "$proto" "$rpc_count"
done

echo
echo "done. commit-ready .proto under gluon/; pb/ is gitignored."
