// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: flags.proto

// Shared flag types for the structured git Subcommand request messages in
// subcommand.proto. Per-command arg messages reuse these so that common
// options (--quiet, --verbose, pathspecs, commit-message source, gpg-sign,
// fast-forward mode, etc.) are spelled the same way everywhere.

package genpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OptBool represents a CLI flag that can be explicitly on (--foo), explicitly
// off (--no-foo), or unset (let git decide). proto3 bool defaults to false
// which loses the unset/explicit-false distinction, so we use an enum.
type OptBool int32

const (
	OptBool_OPT_BOOL_UNSPECIFIED OptBool = 0
	OptBool_OPT_BOOL_TRUE        OptBool = 1 // --foo
	OptBool_OPT_BOOL_FALSE       OptBool = 2 // --no-foo
)

// Enum value maps for OptBool.
var (
	OptBool_name = map[int32]string{
		0: "OPT_BOOL_UNSPECIFIED",
		1: "OPT_BOOL_TRUE",
		2: "OPT_BOOL_FALSE",
	}
	OptBool_value = map[string]int32{
		"OPT_BOOL_UNSPECIFIED": 0,
		"OPT_BOOL_TRUE":        1,
		"OPT_BOOL_FALSE":       2,
	}
)

func (x OptBool) Enum() *OptBool {
	p := new(OptBool)
	*p = x
	return p
}

func (x OptBool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptBool) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[0].Descriptor()
}

func (OptBool) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[0]
}

func (x OptBool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptBool.Descriptor instead.
func (OptBool) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{0}
}

// Fast-forward control for merge/pull/rebase.
type FastForward int32

const (
	FastForward_FAST_FORWARD_UNSPECIFIED FastForward = 0
	FastForward_FAST_FORWARD_ALLOW       FastForward = 1 // --ff (default)
	FastForward_FAST_FORWARD_NEVER       FastForward = 2 // --no-ff
	FastForward_FAST_FORWARD_ONLY        FastForward = 3 // --ff-only
)

// Enum value maps for FastForward.
var (
	FastForward_name = map[int32]string{
		0: "FAST_FORWARD_UNSPECIFIED",
		1: "FAST_FORWARD_ALLOW",
		2: "FAST_FORWARD_NEVER",
		3: "FAST_FORWARD_ONLY",
	}
	FastForward_value = map[string]int32{
		"FAST_FORWARD_UNSPECIFIED": 0,
		"FAST_FORWARD_ALLOW":       1,
		"FAST_FORWARD_NEVER":       2,
		"FAST_FORWARD_ONLY":        3,
	}
)

func (x FastForward) Enum() *FastForward {
	p := new(FastForward)
	*p = x
	return p
}

func (x FastForward) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FastForward) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[1].Descriptor()
}

func (FastForward) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[1]
}

func (x FastForward) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FastForward.Descriptor instead.
func (FastForward) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{1}
}

// `git add --chmod=(+|-)x`.
type ChmodExecutable int32

const (
	ChmodExecutable_CHMOD_EXECUTABLE_UNSPECIFIED ChmodExecutable = 0
	ChmodExecutable_CHMOD_EXECUTABLE_ADD         ChmodExecutable = 1 // +x
	ChmodExecutable_CHMOD_EXECUTABLE_REMOVE      ChmodExecutable = 2 // -x
)

// Enum value maps for ChmodExecutable.
var (
	ChmodExecutable_name = map[int32]string{
		0: "CHMOD_EXECUTABLE_UNSPECIFIED",
		1: "CHMOD_EXECUTABLE_ADD",
		2: "CHMOD_EXECUTABLE_REMOVE",
	}
	ChmodExecutable_value = map[string]int32{
		"CHMOD_EXECUTABLE_UNSPECIFIED": 0,
		"CHMOD_EXECUTABLE_ADD":         1,
		"CHMOD_EXECUTABLE_REMOVE":      2,
	}
)

func (x ChmodExecutable) Enum() *ChmodExecutable {
	p := new(ChmodExecutable)
	*p = x
	return p
}

func (x ChmodExecutable) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChmodExecutable) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[2].Descriptor()
}

func (ChmodExecutable) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[2]
}

func (x ChmodExecutable) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChmodExecutable.Descriptor instead.
func (ChmodExecutable) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{2}
}

// `git commit -u[<mode>]` / `git status -u<mode>`.
type UntrackedFilesMode int32

const (
	UntrackedFilesMode_UNTRACKED_FILES_MODE_UNSPECIFIED UntrackedFilesMode = 0
	UntrackedFilesMode_UNTRACKED_FILES_MODE_NO          UntrackedFilesMode = 1
	UntrackedFilesMode_UNTRACKED_FILES_MODE_NORMAL      UntrackedFilesMode = 2
	UntrackedFilesMode_UNTRACKED_FILES_MODE_ALL         UntrackedFilesMode = 3
)

// Enum value maps for UntrackedFilesMode.
var (
	UntrackedFilesMode_name = map[int32]string{
		0: "UNTRACKED_FILES_MODE_UNSPECIFIED",
		1: "UNTRACKED_FILES_MODE_NO",
		2: "UNTRACKED_FILES_MODE_NORMAL",
		3: "UNTRACKED_FILES_MODE_ALL",
	}
	UntrackedFilesMode_value = map[string]int32{
		"UNTRACKED_FILES_MODE_UNSPECIFIED": 0,
		"UNTRACKED_FILES_MODE_NO":          1,
		"UNTRACKED_FILES_MODE_NORMAL":      2,
		"UNTRACKED_FILES_MODE_ALL":         3,
	}
)

func (x UntrackedFilesMode) Enum() *UntrackedFilesMode {
	p := new(UntrackedFilesMode)
	*p = x
	return p
}

func (x UntrackedFilesMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UntrackedFilesMode) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[3].Descriptor()
}

func (UntrackedFilesMode) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[3]
}

func (x UntrackedFilesMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UntrackedFilesMode.Descriptor instead.
func (UntrackedFilesMode) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{3}
}

// `git status --ignored[=<mode>]`.
type IgnoredMode int32

const (
	IgnoredMode_IGNORED_MODE_UNSPECIFIED IgnoredMode = 0
	IgnoredMode_IGNORED_MODE_TRADITIONAL IgnoredMode = 1
	IgnoredMode_IGNORED_MODE_MATCHING    IgnoredMode = 2
	IgnoredMode_IGNORED_MODE_NO          IgnoredMode = 3
)

// Enum value maps for IgnoredMode.
var (
	IgnoredMode_name = map[int32]string{
		0: "IGNORED_MODE_UNSPECIFIED",
		1: "IGNORED_MODE_TRADITIONAL",
		2: "IGNORED_MODE_MATCHING",
		3: "IGNORED_MODE_NO",
	}
	IgnoredMode_value = map[string]int32{
		"IGNORED_MODE_UNSPECIFIED": 0,
		"IGNORED_MODE_TRADITIONAL": 1,
		"IGNORED_MODE_MATCHING":    2,
		"IGNORED_MODE_NO":          3,
	}
)

func (x IgnoredMode) Enum() *IgnoredMode {
	p := new(IgnoredMode)
	*p = x
	return p
}

func (x IgnoredMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IgnoredMode) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[4].Descriptor()
}

func (IgnoredMode) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[4]
}

func (x IgnoredMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IgnoredMode.Descriptor instead.
func (IgnoredMode) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{4}
}

// `git status --short|--long|--porcelain[=<v>]`.
type StatusFormat int32

const (
	StatusFormat_STATUS_FORMAT_UNSPECIFIED  StatusFormat = 0
	StatusFormat_STATUS_FORMAT_LONG         StatusFormat = 1
	StatusFormat_STATUS_FORMAT_SHORT        StatusFormat = 2
	StatusFormat_STATUS_FORMAT_PORCELAIN_V1 StatusFormat = 3
	StatusFormat_STATUS_FORMAT_PORCELAIN_V2 StatusFormat = 4
)

// Enum value maps for StatusFormat.
var (
	StatusFormat_name = map[int32]string{
		0: "STATUS_FORMAT_UNSPECIFIED",
		1: "STATUS_FORMAT_LONG",
		2: "STATUS_FORMAT_SHORT",
		3: "STATUS_FORMAT_PORCELAIN_V1",
		4: "STATUS_FORMAT_PORCELAIN_V2",
	}
	StatusFormat_value = map[string]int32{
		"STATUS_FORMAT_UNSPECIFIED":  0,
		"STATUS_FORMAT_LONG":         1,
		"STATUS_FORMAT_SHORT":        2,
		"STATUS_FORMAT_PORCELAIN_V1": 3,
		"STATUS_FORMAT_PORCELAIN_V2": 4,
	}
)

func (x StatusFormat) Enum() *StatusFormat {
	p := new(StatusFormat)
	*p = x
	return p
}

func (x StatusFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[5].Descriptor()
}

func (StatusFormat) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[5]
}

func (x StatusFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusFormat.Descriptor instead.
func (StatusFormat) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{5}
}

// `git log`/`git show` style --decorate[=short|full|auto|no].
type Decorate int32

const (
	Decorate_DECORATE_UNSPECIFIED Decorate = 0
	Decorate_DECORATE_SHORT       Decorate = 1
	Decorate_DECORATE_FULL        Decorate = 2
	Decorate_DECORATE_AUTO        Decorate = 3
	Decorate_DECORATE_NO          Decorate = 4
)

// Enum value maps for Decorate.
var (
	Decorate_name = map[int32]string{
		0: "DECORATE_UNSPECIFIED",
		1: "DECORATE_SHORT",
		2: "DECORATE_FULL",
		3: "DECORATE_AUTO",
		4: "DECORATE_NO",
	}
	Decorate_value = map[string]int32{
		"DECORATE_UNSPECIFIED": 0,
		"DECORATE_SHORT":       1,
		"DECORATE_FULL":        2,
		"DECORATE_AUTO":        3,
		"DECORATE_NO":          4,
	}
)

func (x Decorate) Enum() *Decorate {
	p := new(Decorate)
	*p = x
	return p
}

func (x Decorate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decorate) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[6].Descriptor()
}

func (Decorate) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[6]
}

func (x Decorate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decorate.Descriptor instead.
func (Decorate) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{6}
}

// `--color[=<when>]` shared by branch/log/diff/etc.
type ColorWhen int32

const (
	ColorWhen_COLOR_WHEN_UNSPECIFIED ColorWhen = 0
	ColorWhen_COLOR_WHEN_ALWAYS      ColorWhen = 1
	ColorWhen_COLOR_WHEN_NEVER       ColorWhen = 2
	ColorWhen_COLOR_WHEN_AUTO        ColorWhen = 3
)

// Enum value maps for ColorWhen.
var (
	ColorWhen_name = map[int32]string{
		0: "COLOR_WHEN_UNSPECIFIED",
		1: "COLOR_WHEN_ALWAYS",
		2: "COLOR_WHEN_NEVER",
		3: "COLOR_WHEN_AUTO",
	}
	ColorWhen_value = map[string]int32{
		"COLOR_WHEN_UNSPECIFIED": 0,
		"COLOR_WHEN_ALWAYS":      1,
		"COLOR_WHEN_NEVER":       2,
		"COLOR_WHEN_AUTO":        3,
	}
)

func (x ColorWhen) Enum() *ColorWhen {
	p := new(ColorWhen)
	*p = x
	return p
}

func (x ColorWhen) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorWhen) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[7].Descriptor()
}

func (ColorWhen) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[7]
}

func (x ColorWhen) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorWhen.Descriptor instead.
func (ColorWhen) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{7}
}

// `git branch --track[=(direct|inherit)]`.
type BranchTrackMode int32

const (
	BranchTrackMode_BRANCH_TRACK_MODE_UNSPECIFIED BranchTrackMode = 0
	BranchTrackMode_BRANCH_TRACK_MODE_DIRECT      BranchTrackMode = 1
	BranchTrackMode_BRANCH_TRACK_MODE_INHERIT     BranchTrackMode = 2
	BranchTrackMode_BRANCH_TRACK_MODE_NO          BranchTrackMode = 3 // --no-track
)

// Enum value maps for BranchTrackMode.
var (
	BranchTrackMode_name = map[int32]string{
		0: "BRANCH_TRACK_MODE_UNSPECIFIED",
		1: "BRANCH_TRACK_MODE_DIRECT",
		2: "BRANCH_TRACK_MODE_INHERIT",
		3: "BRANCH_TRACK_MODE_NO",
	}
	BranchTrackMode_value = map[string]int32{
		"BRANCH_TRACK_MODE_UNSPECIFIED": 0,
		"BRANCH_TRACK_MODE_DIRECT":      1,
		"BRANCH_TRACK_MODE_INHERIT":     2,
		"BRANCH_TRACK_MODE_NO":          3,
	}
)

func (x BranchTrackMode) Enum() *BranchTrackMode {
	p := new(BranchTrackMode)
	*p = x
	return p
}

func (x BranchTrackMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BranchTrackMode) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[8].Descriptor()
}

func (BranchTrackMode) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[8]
}

func (x BranchTrackMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BranchTrackMode.Descriptor instead.
func (BranchTrackMode) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{8}
}

// `--recurse-submodules[=<mode>]`.
type RecurseSubmodules int32

const (
	RecurseSubmodules_RECURSE_SUBMODULES_UNSPECIFIED RecurseSubmodules = 0
	RecurseSubmodules_RECURSE_SUBMODULES_NO          RecurseSubmodules = 1
	RecurseSubmodules_RECURSE_SUBMODULES_YES         RecurseSubmodules = 2
	RecurseSubmodules_RECURSE_SUBMODULES_ON_DEMAND   RecurseSubmodules = 3
	RecurseSubmodules_RECURSE_SUBMODULES_CHECK       RecurseSubmodules = 4
	RecurseSubmodules_RECURSE_SUBMODULES_ONLY        RecurseSubmodules = 5
)

// Enum value maps for RecurseSubmodules.
var (
	RecurseSubmodules_name = map[int32]string{
		0: "RECURSE_SUBMODULES_UNSPECIFIED",
		1: "RECURSE_SUBMODULES_NO",
		2: "RECURSE_SUBMODULES_YES",
		3: "RECURSE_SUBMODULES_ON_DEMAND",
		4: "RECURSE_SUBMODULES_CHECK",
		5: "RECURSE_SUBMODULES_ONLY",
	}
	RecurseSubmodules_value = map[string]int32{
		"RECURSE_SUBMODULES_UNSPECIFIED": 0,
		"RECURSE_SUBMODULES_NO":          1,
		"RECURSE_SUBMODULES_YES":         2,
		"RECURSE_SUBMODULES_ON_DEMAND":   3,
		"RECURSE_SUBMODULES_CHECK":       4,
		"RECURSE_SUBMODULES_ONLY":        5,
	}
)

func (x RecurseSubmodules) Enum() *RecurseSubmodules {
	p := new(RecurseSubmodules)
	*p = x
	return p
}

func (x RecurseSubmodules) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecurseSubmodules) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[9].Descriptor()
}

func (RecurseSubmodules) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[9]
}

func (x RecurseSubmodules) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecurseSubmodules.Descriptor instead.
func (RecurseSubmodules) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{9}
}

// Pathspec group: positional pathspecs plus the optional file-based source.
// Used wherever the git CLI ends with `[--] [<pathspec>...]` and accepts
// --pathspec-from-file / --pathspec-file-nul.
type Pathspec struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Pathspec []string               `protobuf:"bytes,1,rep,name=pathspec,proto3" json:"pathspec,omitempty"`
	// Absolute/relative path to a file whose contents are pathspec entries.
	PathspecFromFile string `protobuf:"bytes,2,opt,name=pathspec_from_file,json=pathspecFromFile,proto3" json:"pathspec_from_file,omitempty"`
	// Only valid with pathspec_from_file; separates entries by NUL instead of LF.
	PathspecFileNul OptBool `protobuf:"varint,3,opt,name=pathspec_file_nul,json=pathspecFileNul,proto3,enum=subcommands.OptBool" json:"pathspec_file_nul,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Pathspec) Reset() {
	*x = Pathspec{}
	mi := &file_flags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pathspec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pathspec) ProtoMessage() {}

func (x *Pathspec) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pathspec.ProtoReflect.Descriptor instead.
func (*Pathspec) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{0}
}

func (x *Pathspec) GetPathspec() []string {
	if x != nil {
		return x.Pathspec
	}
	return nil
}

func (x *Pathspec) GetPathspecFromFile() string {
	if x != nil {
		return x.PathspecFromFile
	}
	return ""
}

func (x *Pathspec) GetPathspecFileNul() OptBool {
	if x != nil {
		return x.PathspecFileNul
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

// Commit message source: -m, -F, -C, -c, --squash, --fixup. At most one is
// meaningful per invocation; the server defers semantic validation to git.
type MessageSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// -m / --message (repeated is legal — git concatenates as paragraphs).
	Message []string `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	// -F / --file <file>
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// -C / --reuse-message <commit>
	ReuseMessage string `protobuf:"bytes,3,opt,name=reuse_message,json=reuseMessage,proto3" json:"reuse_message,omitempty"`
	// -c / --reedit-message <commit>
	ReeditMessage string `protobuf:"bytes,4,opt,name=reedit_message,json=reeditMessage,proto3" json:"reedit_message,omitempty"`
	// --squash <commit>
	Squash string `protobuf:"bytes,5,opt,name=squash,proto3" json:"squash,omitempty"`
	// --fixup [(amend|reword):]<commit>
	Fixup string `protobuf:"bytes,6,opt,name=fixup,proto3" json:"fixup,omitempty"`
	// -t / --template <file>
	Template      string `protobuf:"bytes,7,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSource) Reset() {
	*x = MessageSource{}
	mi := &file_flags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSource) ProtoMessage() {}

func (x *MessageSource) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSource.ProtoReflect.Descriptor instead.
func (*MessageSource) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSource) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageSource) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *MessageSource) GetReuseMessage() string {
	if x != nil {
		return x.ReuseMessage
	}
	return ""
}

func (x *MessageSource) GetReeditMessage() string {
	if x != nil {
		return x.ReeditMessage
	}
	return ""
}

func (x *MessageSource) GetSquash() string {
	if x != nil {
		return x.Squash
	}
	return ""
}

func (x *MessageSource) GetFixup() string {
	if x != nil {
		return x.Fixup
	}
	return ""
}

func (x *MessageSource) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

// GPG-sign option: -S[<keyid>] / --gpg-sign[=<keyid>] or --no-gpg-sign.
type GpgSign struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UNSPECIFIED = don't pass a flag; TRUE = sign; FALSE = --no-gpg-sign.
	Sign OptBool `protobuf:"varint,1,opt,name=sign,proto3,enum=subcommands.OptBool" json:"sign,omitempty"`
	// Optional key id (only meaningful when sign == TRUE).
	KeyId         string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpgSign) Reset() {
	*x = GpgSign{}
	mi := &file_flags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpgSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpgSign) ProtoMessage() {}

func (x *GpgSign) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpgSign.ProtoReflect.Descriptor instead.
func (*GpgSign) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{2}
}

func (x *GpgSign) GetSign() OptBool {
	if x != nil {
		return x.Sign
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *GpgSign) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// Identity override: --author=<author>, --date=<date>. Commit/rebase/etc.
type IdentityOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityOverride) Reset() {
	*x = IdentityOverride{}
	mi := &file_flags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityOverride) ProtoMessage() {}

func (x *IdentityOverride) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityOverride.ProtoReflect.Descriptor instead.
func (*IdentityOverride) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityOverride) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *IdentityOverride) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// OptInt is the int counterpart of OptBool: distinguishes "unset" from any
// explicit numeric value (including 0). Used for flags like --unified=<n>,
// --abbrev=<n>, --inter-hunk-context=<n>, -l<num> where 0 is a legal value.
type OptInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptInt) Reset() {
	*x = OptInt{}
	mi := &file_flags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptInt) ProtoMessage() {}

func (x *OptInt) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptInt.ProtoReflect.Descriptor instead.
func (*OptInt) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{4}
}

func (x *OptInt) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *OptInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// DiffFormatting is the full set of options shared by every command that
// renders a diff (git diff, git log, git show, git format-patch, etc.). Pull
// this into an arg message to get every formatting knob in one place.
//
// Source: `git diff --help` OPTIONS section (git 2.39). Every flag listed
// there — including the niche whitespace / rename-detection / dirstat knobs
// — is represented below. Flags that take a value are `string` (empty =
// unset) unless 0 is a legal numeric value, in which case they use OptInt.
type DiffFormatting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---- Output shape ------------------------------------------------------
	Patch                  OptBool `protobuf:"varint,1,opt,name=patch,proto3,enum=subcommands.OptBool" json:"patch,omitempty"`                                         // -p / -u / --patch
	NoPatch                OptBool `protobuf:"varint,2,opt,name=no_patch,json=noPatch,proto3,enum=subcommands.OptBool" json:"no_patch,omitempty"`                      // -s / --no-patch
	Unified                *OptInt `protobuf:"bytes,3,opt,name=unified,proto3" json:"unified,omitempty"`                                                               // -U<n> / --unified=<n>
	Output                 string  `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`                                                                 // --output=<file>
	OutputIndicatorNew     string  `protobuf:"bytes,5,opt,name=output_indicator_new,json=outputIndicatorNew,proto3" json:"output_indicator_new,omitempty"`             // --output-indicator-new=<char>
	OutputIndicatorOld     string  `protobuf:"bytes,6,opt,name=output_indicator_old,json=outputIndicatorOld,proto3" json:"output_indicator_old,omitempty"`             // --output-indicator-old=<char>
	OutputIndicatorContext string  `protobuf:"bytes,7,opt,name=output_indicator_context,json=outputIndicatorContext,proto3" json:"output_indicator_context,omitempty"` // --output-indicator-context=<char>
	Raw                    OptBool `protobuf:"varint,8,opt,name=raw,proto3,enum=subcommands.OptBool" json:"raw,omitempty"`                                             // --raw
	PatchWithRaw           OptBool `protobuf:"varint,9,opt,name=patch_with_raw,json=patchWithRaw,proto3,enum=subcommands.OptBool" json:"patch_with_raw,omitempty"`     // --patch-with-raw
	// ---- Algorithm ---------------------------------------------------------
	IndentHeuristic OptBool  `protobuf:"varint,10,opt,name=indent_heuristic,json=indentHeuristic,proto3,enum=subcommands.OptBool" json:"indent_heuristic,omitempty"` // --[no-]indent-heuristic
	Minimal         OptBool  `protobuf:"varint,11,opt,name=minimal,proto3,enum=subcommands.OptBool" json:"minimal,omitempty"`                                        // --minimal
	Patience        OptBool  `protobuf:"varint,12,opt,name=patience,proto3,enum=subcommands.OptBool" json:"patience,omitempty"`                                      // --patience
	Histogram       OptBool  `protobuf:"varint,13,opt,name=histogram,proto3,enum=subcommands.OptBool" json:"histogram,omitempty"`                                    // --histogram
	Anchored        []string `protobuf:"bytes,14,rep,name=anchored,proto3" json:"anchored,omitempty"`                                                                // --anchored=<text> (repeatable)
	DiffAlgorithm   string   `protobuf:"bytes,15,opt,name=diff_algorithm,json=diffAlgorithm,proto3" json:"diff_algorithm,omitempty"`                                 // --diff-algorithm={patience|minimal|histogram|myers}
	// ---- Stat / summary variants ------------------------------------------
	Stat                OptBool `protobuf:"varint,16,opt,name=stat,proto3,enum=subcommands.OptBool" json:"stat,omitempty"`                                           // --stat (flag only)
	StatSpec            string  `protobuf:"bytes,17,opt,name=stat_spec,json=statSpec,proto3" json:"stat_spec,omitempty"`                                             // optional "=<width>[,<name-width>[,<count>]]"
	StatWidth           *OptInt `protobuf:"bytes,18,opt,name=stat_width,json=statWidth,proto3" json:"stat_width,omitempty"`                                          // --stat-width=<n>
	StatNameWidth       *OptInt `protobuf:"bytes,19,opt,name=stat_name_width,json=statNameWidth,proto3" json:"stat_name_width,omitempty"`                            // --stat-name-width=<n>
	StatCount           *OptInt `protobuf:"bytes,20,opt,name=stat_count,json=statCount,proto3" json:"stat_count,omitempty"`                                          // --stat-count=<n>
	CompactSummary      OptBool `protobuf:"varint,21,opt,name=compact_summary,json=compactSummary,proto3,enum=subcommands.OptBool" json:"compact_summary,omitempty"` // --compact-summary
	Numstat             OptBool `protobuf:"varint,22,opt,name=numstat,proto3,enum=subcommands.OptBool" json:"numstat,omitempty"`                                     // --numstat
	Shortstat           OptBool `protobuf:"varint,23,opt,name=shortstat,proto3,enum=subcommands.OptBool" json:"shortstat,omitempty"`                                 // --shortstat
	Dirstat             OptBool `protobuf:"varint,24,opt,name=dirstat,proto3,enum=subcommands.OptBool" json:"dirstat,omitempty"`                                     // -X / --dirstat (flag only)
	DirstatParams       string  `protobuf:"bytes,25,opt,name=dirstat_params,json=dirstatParams,proto3" json:"dirstat_params,omitempty"`                              // optional "=<param1,param2,...>"
	Cumulative          OptBool `protobuf:"varint,26,opt,name=cumulative,proto3,enum=subcommands.OptBool" json:"cumulative,omitempty"`                               // --cumulative
	DirstatByFile       OptBool `protobuf:"varint,27,opt,name=dirstat_by_file,json=dirstatByFile,proto3,enum=subcommands.OptBool" json:"dirstat_by_file,omitempty"`  // --dirstat-by-file (flag only)
	DirstatByFileParams string  `protobuf:"bytes,28,opt,name=dirstat_by_file_params,json=dirstatByFileParams,proto3" json:"dirstat_by_file_params,omitempty"`        // optional params
	Summary             OptBool `protobuf:"varint,29,opt,name=summary,proto3,enum=subcommands.OptBool" json:"summary,omitempty"`                                     // --summary
	PatchWithStat       OptBool `protobuf:"varint,30,opt,name=patch_with_stat,json=patchWithStat,proto3,enum=subcommands.OptBool" json:"patch_with_stat,omitempty"`  // --patch-with-stat
	Z                   OptBool `protobuf:"varint,31,opt,name=z,proto3,enum=subcommands.OptBool" json:"z,omitempty"`                                                 // -z
	NameOnly            OptBool `protobuf:"varint,32,opt,name=name_only,json=nameOnly,proto3,enum=subcommands.OptBool" json:"name_only,omitempty"`                   // --name-only
	NameStatus          OptBool `protobuf:"varint,33,opt,name=name_status,json=nameStatus,proto3,enum=subcommands.OptBool" json:"name_status,omitempty"`             // --name-status
	Submodule           OptBool `protobuf:"varint,34,opt,name=submodule,proto3,enum=subcommands.OptBool" json:"submodule,omitempty"`                                 // --submodule (flag only)
	SubmoduleFormat     string  `protobuf:"bytes,35,opt,name=submodule_format,json=submoduleFormat,proto3" json:"submodule_format,omitempty"`                        // --submodule=<format>
	// ---- Color / word-diff ------------------------------------------------
	Color           ColorWhen `protobuf:"varint,36,opt,name=color,proto3,enum=subcommands.ColorWhen" json:"color,omitempty"`                                           // --color[=<when>] (ALWAYS/NEVER/AUTO)
	ColorFlag       OptBool   `protobuf:"varint,37,opt,name=color_flag,json=colorFlag,proto3,enum=subcommands.OptBool" json:"color_flag,omitempty"`                    // plain --color (no =<when>)
	NoColor         OptBool   `protobuf:"varint,38,opt,name=no_color,json=noColor,proto3,enum=subcommands.OptBool" json:"no_color,omitempty"`                          // --no-color (redundant with color=NEVER)
	ColorMoved      OptBool   `protobuf:"varint,39,opt,name=color_moved,json=colorMoved,proto3,enum=subcommands.OptBool" json:"color_moved,omitempty"`                 // --color-moved flag only
	ColorMovedMode  string    `protobuf:"bytes,40,opt,name=color_moved_mode,json=colorMovedMode,proto3" json:"color_moved_mode,omitempty"`                             // --color-moved=<mode>
	NoColorMoved    OptBool   `protobuf:"varint,41,opt,name=no_color_moved,json=noColorMoved,proto3,enum=subcommands.OptBool" json:"no_color_moved,omitempty"`         // --no-color-moved
	ColorMovedWs    string    `protobuf:"bytes,42,opt,name=color_moved_ws,json=colorMovedWs,proto3" json:"color_moved_ws,omitempty"`                                   // --color-moved-ws=<modes>
	NoColorMovedWs  OptBool   `protobuf:"varint,43,opt,name=no_color_moved_ws,json=noColorMovedWs,proto3,enum=subcommands.OptBool" json:"no_color_moved_ws,omitempty"` // --no-color-moved-ws
	WordDiff        OptBool   `protobuf:"varint,44,opt,name=word_diff,json=wordDiff,proto3,enum=subcommands.OptBool" json:"word_diff,omitempty"`                       // --word-diff flag only
	WordDiffMode    string    `protobuf:"bytes,45,opt,name=word_diff_mode,json=wordDiffMode,proto3" json:"word_diff_mode,omitempty"`                                   // --word-diff=<mode>
	WordDiffRegex   string    `protobuf:"bytes,46,opt,name=word_diff_regex,json=wordDiffRegex,proto3" json:"word_diff_regex,omitempty"`                                // --word-diff-regex=<regex>
	ColorWords      OptBool   `protobuf:"varint,47,opt,name=color_words,json=colorWords,proto3,enum=subcommands.OptBool" json:"color_words,omitempty"`                 // --color-words flag only
	ColorWordsRegex string    `protobuf:"bytes,48,opt,name=color_words_regex,json=colorWordsRegex,proto3" json:"color_words_regex,omitempty"`                          // --color-words=<regex>
	// ---- Rename / copy detection / rewrite --------------------------------
	NoRenames          OptBool `protobuf:"varint,49,opt,name=no_renames,json=noRenames,proto3,enum=subcommands.OptBool" json:"no_renames,omitempty"`       // --no-renames
	RenameEmpty        OptBool `protobuf:"varint,50,opt,name=rename_empty,json=renameEmpty,proto3,enum=subcommands.OptBool" json:"rename_empty,omitempty"` // --[no-]rename-empty
	Check              OptBool `protobuf:"varint,51,opt,name=check,proto3,enum=subcommands.OptBool" json:"check,omitempty"`                                // --check
	WsErrorHighlight   string  `protobuf:"bytes,52,opt,name=ws_error_highlight,json=wsErrorHighlight,proto3" json:"ws_error_highlight,omitempty"`          // --ws-error-highlight=<kind>
	FullIndex          OptBool `protobuf:"varint,53,opt,name=full_index,json=fullIndex,proto3,enum=subcommands.OptBool" json:"full_index,omitempty"`       // --full-index
	Binary             OptBool `protobuf:"varint,54,opt,name=binary,proto3,enum=subcommands.OptBool" json:"binary,omitempty"`                              // --binary
	Abbrev             *OptInt `protobuf:"bytes,55,opt,name=abbrev,proto3" json:"abbrev,omitempty"`                                                        // --abbrev[=<n>]
	NoAbbrev           OptBool `protobuf:"varint,56,opt,name=no_abbrev,json=noAbbrev,proto3,enum=subcommands.OptBool" json:"no_abbrev,omitempty"`          // --no-abbrev
	BreakRewrites      string  `protobuf:"bytes,57,opt,name=break_rewrites,json=breakRewrites,proto3" json:"break_rewrites,omitempty"`                     // -B[<n>][/<m>] / --break-rewrites — passed as raw spec
	FindRenames        string  `protobuf:"bytes,58,opt,name=find_renames,json=findRenames,proto3" json:"find_renames,omitempty"`                           // -M[<n>] / --find-renames[=<n>]
	FindCopies         string  `protobuf:"bytes,59,opt,name=find_copies,json=findCopies,proto3" json:"find_copies,omitempty"`                              // -C[<n>] / --find-copies[=<n>]
	FindCopiesHarder   OptBool `protobuf:"varint,60,opt,name=find_copies_harder,json=findCopiesHarder,proto3,enum=subcommands.OptBool" json:"find_copies_harder,omitempty"`
	IrreversibleDelete OptBool `protobuf:"varint,61,opt,name=irreversible_delete,json=irreversibleDelete,proto3,enum=subcommands.OptBool" json:"irreversible_delete,omitempty"` // -D
	RenameLimit        *OptInt `protobuf:"bytes,62,opt,name=rename_limit,json=renameLimit,proto3" json:"rename_limit,omitempty"`                                                // -l<num>
	DiffFilter         string  `protobuf:"bytes,63,opt,name=diff_filter,json=diffFilter,proto3" json:"diff_filter,omitempty"`                                                   // --diff-filter=<filter>
	PickaxeS           string  `protobuf:"bytes,64,opt,name=pickaxe_s,json=pickaxeS,proto3" json:"pickaxe_s,omitempty"`                                                         // -S<string>
	PickaxeG           string  `protobuf:"bytes,65,opt,name=pickaxe_g,json=pickaxeG,proto3" json:"pickaxe_g,omitempty"`                                                         // -G<regex>
	FindObject         string  `protobuf:"bytes,66,opt,name=find_object,json=findObject,proto3" json:"find_object,omitempty"`                                                   // --find-object=<oid>
	PickaxeAll         OptBool `protobuf:"varint,67,opt,name=pickaxe_all,json=pickaxeAll,proto3,enum=subcommands.OptBool" json:"pickaxe_all,omitempty"`
	PickaxeRegex       OptBool `protobuf:"varint,68,opt,name=pickaxe_regex,json=pickaxeRegex,proto3,enum=subcommands.OptBool" json:"pickaxe_regex,omitempty"`
	Orderfile          string  `protobuf:"bytes,69,opt,name=orderfile,proto3" json:"orderfile,omitempty"`                       // -O<orderfile>
	SkipTo             string  `protobuf:"bytes,70,opt,name=skip_to,json=skipTo,proto3" json:"skip_to,omitempty"`               // --skip-to=<file>
	RotateTo           string  `protobuf:"bytes,71,opt,name=rotate_to,json=rotateTo,proto3" json:"rotate_to,omitempty"`         // --rotate-to=<file>
	Reverse            OptBool `protobuf:"varint,72,opt,name=reverse,proto3,enum=subcommands.OptBool" json:"reverse,omitempty"` // -R
	// ---- Path / relative --------------------------------------------------
	Relative     OptBool `protobuf:"varint,73,opt,name=relative,proto3,enum=subcommands.OptBool" json:"relative,omitempty"`                       // --relative (flag only)
	RelativePath string  `protobuf:"bytes,74,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`                     // --relative=<path>
	NoRelative   OptBool `protobuf:"varint,75,opt,name=no_relative,json=noRelative,proto3,enum=subcommands.OptBool" json:"no_relative,omitempty"` // --no-relative
	// ---- Whitespace -------------------------------------------------------
	Text                OptBool  `protobuf:"varint,76,opt,name=text,proto3,enum=subcommands.OptBool" json:"text,omitempty"` // -a / --text
	IgnoreCrAtEol       OptBool  `protobuf:"varint,77,opt,name=ignore_cr_at_eol,json=ignoreCrAtEol,proto3,enum=subcommands.OptBool" json:"ignore_cr_at_eol,omitempty"`
	IgnoreSpaceAtEol    OptBool  `protobuf:"varint,78,opt,name=ignore_space_at_eol,json=ignoreSpaceAtEol,proto3,enum=subcommands.OptBool" json:"ignore_space_at_eol,omitempty"`
	IgnoreSpaceChange   OptBool  `protobuf:"varint,79,opt,name=ignore_space_change,json=ignoreSpaceChange,proto3,enum=subcommands.OptBool" json:"ignore_space_change,omitempty"` // -b
	IgnoreAllSpace      OptBool  `protobuf:"varint,80,opt,name=ignore_all_space,json=ignoreAllSpace,proto3,enum=subcommands.OptBool" json:"ignore_all_space,omitempty"`          // -w
	IgnoreBlankLines    OptBool  `protobuf:"varint,81,opt,name=ignore_blank_lines,json=ignoreBlankLines,proto3,enum=subcommands.OptBool" json:"ignore_blank_lines,omitempty"`
	IgnoreMatchingLines []string `protobuf:"bytes,82,rep,name=ignore_matching_lines,json=ignoreMatchingLines,proto3" json:"ignore_matching_lines,omitempty"`             // -I<regex> / --ignore-matching-lines=<regex>
	InterHunkContext    *OptInt  `protobuf:"bytes,83,opt,name=inter_hunk_context,json=interHunkContext,proto3" json:"inter_hunk_context,omitempty"`                      // --inter-hunk-context=<n>
	FunctionContext     OptBool  `protobuf:"varint,84,opt,name=function_context,json=functionContext,proto3,enum=subcommands.OptBool" json:"function_context,omitempty"` // -W
	// ---- Exit / external / textconv ---------------------------------------
	ExitCode  OptBool `protobuf:"varint,85,opt,name=exit_code,json=exitCode,proto3,enum=subcommands.OptBool" json:"exit_code,omitempty"`
	Quiet     OptBool `protobuf:"varint,86,opt,name=quiet,proto3,enum=subcommands.OptBool" json:"quiet,omitempty"`                    // --quiet
	ExtDiff   OptBool `protobuf:"varint,87,opt,name=ext_diff,json=extDiff,proto3,enum=subcommands.OptBool" json:"ext_diff,omitempty"` // --ext-diff
	NoExtDiff OptBool `protobuf:"varint,88,opt,name=no_ext_diff,json=noExtDiff,proto3,enum=subcommands.OptBool" json:"no_ext_diff,omitempty"`
	Textconv  OptBool `protobuf:"varint,89,opt,name=textconv,proto3,enum=subcommands.OptBool" json:"textconv,omitempty"` // --[no-]textconv
	// ---- Submodules / prefixes --------------------------------------------
	IgnoreSubmodules     OptBool `protobuf:"varint,90,opt,name=ignore_submodules,json=ignoreSubmodules,proto3,enum=subcommands.OptBool" json:"ignore_submodules,omitempty"` // --ignore-submodules (flag only)
	IgnoreSubmodulesWhen string  `protobuf:"bytes,91,opt,name=ignore_submodules_when,json=ignoreSubmodulesWhen,proto3" json:"ignore_submodules_when,omitempty"`             // --ignore-submodules=<when>
	SrcPrefix            string  `protobuf:"bytes,92,opt,name=src_prefix,json=srcPrefix,proto3" json:"src_prefix,omitempty"`
	DstPrefix            string  `protobuf:"bytes,93,opt,name=dst_prefix,json=dstPrefix,proto3" json:"dst_prefix,omitempty"`
	NoPrefix             OptBool `protobuf:"varint,94,opt,name=no_prefix,json=noPrefix,proto3,enum=subcommands.OptBool" json:"no_prefix,omitempty"`
	LinePrefix           string  `protobuf:"bytes,95,opt,name=line_prefix,json=linePrefix,proto3" json:"line_prefix,omitempty"`
	ItaInvisibleInIndex  OptBool `protobuf:"varint,96,opt,name=ita_invisible_in_index,json=itaInvisibleInIndex,proto3,enum=subcommands.OptBool" json:"ita_invisible_in_index,omitempty"`
	ItaVisibleInIndex    OptBool `protobuf:"varint,97,opt,name=ita_visible_in_index,json=itaVisibleInIndex,proto3,enum=subcommands.OptBool" json:"ita_visible_in_index,omitempty"` // --ita-visible-in-index
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DiffFormatting) Reset() {
	*x = DiffFormatting{}
	mi := &file_flags_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffFormatting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffFormatting) ProtoMessage() {}

func (x *DiffFormatting) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffFormatting.ProtoReflect.Descriptor instead.
func (*DiffFormatting) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{5}
}

func (x *DiffFormatting) GetPatch() OptBool {
	if x != nil {
		return x.Patch
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetNoPatch() OptBool {
	if x != nil {
		return x.NoPatch
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetUnified() *OptInt {
	if x != nil {
		return x.Unified
	}
	return nil
}

func (x *DiffFormatting) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DiffFormatting) GetOutputIndicatorNew() string {
	if x != nil {
		return x.OutputIndicatorNew
	}
	return ""
}

func (x *DiffFormatting) GetOutputIndicatorOld() string {
	if x != nil {
		return x.OutputIndicatorOld
	}
	return ""
}

func (x *DiffFormatting) GetOutputIndicatorContext() string {
	if x != nil {
		return x.OutputIndicatorContext
	}
	return ""
}

func (x *DiffFormatting) GetRaw() OptBool {
	if x != nil {
		return x.Raw
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetPatchWithRaw() OptBool {
	if x != nil {
		return x.PatchWithRaw
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIndentHeuristic() OptBool {
	if x != nil {
		return x.IndentHeuristic
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetMinimal() OptBool {
	if x != nil {
		return x.Minimal
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetPatience() OptBool {
	if x != nil {
		return x.Patience
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetHistogram() OptBool {
	if x != nil {
		return x.Histogram
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetAnchored() []string {
	if x != nil {
		return x.Anchored
	}
	return nil
}

func (x *DiffFormatting) GetDiffAlgorithm() string {
	if x != nil {
		return x.DiffAlgorithm
	}
	return ""
}

func (x *DiffFormatting) GetStat() OptBool {
	if x != nil {
		return x.Stat
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetStatSpec() string {
	if x != nil {
		return x.StatSpec
	}
	return ""
}

func (x *DiffFormatting) GetStatWidth() *OptInt {
	if x != nil {
		return x.StatWidth
	}
	return nil
}

func (x *DiffFormatting) GetStatNameWidth() *OptInt {
	if x != nil {
		return x.StatNameWidth
	}
	return nil
}

func (x *DiffFormatting) GetStatCount() *OptInt {
	if x != nil {
		return x.StatCount
	}
	return nil
}

func (x *DiffFormatting) GetCompactSummary() OptBool {
	if x != nil {
		return x.CompactSummary
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetNumstat() OptBool {
	if x != nil {
		return x.Numstat
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetShortstat() OptBool {
	if x != nil {
		return x.Shortstat
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetDirstat() OptBool {
	if x != nil {
		return x.Dirstat
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetDirstatParams() string {
	if x != nil {
		return x.DirstatParams
	}
	return ""
}

func (x *DiffFormatting) GetCumulative() OptBool {
	if x != nil {
		return x.Cumulative
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetDirstatByFile() OptBool {
	if x != nil {
		return x.DirstatByFile
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetDirstatByFileParams() string {
	if x != nil {
		return x.DirstatByFileParams
	}
	return ""
}

func (x *DiffFormatting) GetSummary() OptBool {
	if x != nil {
		return x.Summary
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetPatchWithStat() OptBool {
	if x != nil {
		return x.PatchWithStat
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetZ() OptBool {
	if x != nil {
		return x.Z
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetNameOnly() OptBool {
	if x != nil {
		return x.NameOnly
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetNameStatus() OptBool {
	if x != nil {
		return x.NameStatus
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetSubmodule() OptBool {
	if x != nil {
		return x.Submodule
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetSubmoduleFormat() string {
	if x != nil {
		return x.SubmoduleFormat
	}
	return ""
}

func (x *DiffFormatting) GetColor() ColorWhen {
	if x != nil {
		return x.Color
	}
	return ColorWhen_COLOR_WHEN_UNSPECIFIED
}

func (x *DiffFormatting) GetColorFlag() OptBool {
	if x != nil {
		return x.ColorFlag
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetNoColor() OptBool {
	if x != nil {
		return x.NoColor
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetColorMoved() OptBool {
	if x != nil {
		return x.ColorMoved
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetColorMovedMode() string {
	if x != nil {
		return x.ColorMovedMode
	}
	return ""
}

func (x *DiffFormatting) GetNoColorMoved() OptBool {
	if x != nil {
		return x.NoColorMoved
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetColorMovedWs() string {
	if x != nil {
		return x.ColorMovedWs
	}
	return ""
}

func (x *DiffFormatting) GetNoColorMovedWs() OptBool {
	if x != nil {
		return x.NoColorMovedWs
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetWordDiff() OptBool {
	if x != nil {
		return x.WordDiff
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetWordDiffMode() string {
	if x != nil {
		return x.WordDiffMode
	}
	return ""
}

func (x *DiffFormatting) GetWordDiffRegex() string {
	if x != nil {
		return x.WordDiffRegex
	}
	return ""
}

func (x *DiffFormatting) GetColorWords() OptBool {
	if x != nil {
		return x.ColorWords
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetColorWordsRegex() string {
	if x != nil {
		return x.ColorWordsRegex
	}
	return ""
}

func (x *DiffFormatting) GetNoRenames() OptBool {
	if x != nil {
		return x.NoRenames
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetRenameEmpty() OptBool {
	if x != nil {
		return x.RenameEmpty
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetCheck() OptBool {
	if x != nil {
		return x.Check
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetWsErrorHighlight() string {
	if x != nil {
		return x.WsErrorHighlight
	}
	return ""
}

func (x *DiffFormatting) GetFullIndex() OptBool {
	if x != nil {
		return x.FullIndex
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetBinary() OptBool {
	if x != nil {
		return x.Binary
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetAbbrev() *OptInt {
	if x != nil {
		return x.Abbrev
	}
	return nil
}

func (x *DiffFormatting) GetNoAbbrev() OptBool {
	if x != nil {
		return x.NoAbbrev
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetBreakRewrites() string {
	if x != nil {
		return x.BreakRewrites
	}
	return ""
}

func (x *DiffFormatting) GetFindRenames() string {
	if x != nil {
		return x.FindRenames
	}
	return ""
}

func (x *DiffFormatting) GetFindCopies() string {
	if x != nil {
		return x.FindCopies
	}
	return ""
}

func (x *DiffFormatting) GetFindCopiesHarder() OptBool {
	if x != nil {
		return x.FindCopiesHarder
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIrreversibleDelete() OptBool {
	if x != nil {
		return x.IrreversibleDelete
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetRenameLimit() *OptInt {
	if x != nil {
		return x.RenameLimit
	}
	return nil
}

func (x *DiffFormatting) GetDiffFilter() string {
	if x != nil {
		return x.DiffFilter
	}
	return ""
}

func (x *DiffFormatting) GetPickaxeS() string {
	if x != nil {
		return x.PickaxeS
	}
	return ""
}

func (x *DiffFormatting) GetPickaxeG() string {
	if x != nil {
		return x.PickaxeG
	}
	return ""
}

func (x *DiffFormatting) GetFindObject() string {
	if x != nil {
		return x.FindObject
	}
	return ""
}

func (x *DiffFormatting) GetPickaxeAll() OptBool {
	if x != nil {
		return x.PickaxeAll
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetPickaxeRegex() OptBool {
	if x != nil {
		return x.PickaxeRegex
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetOrderfile() string {
	if x != nil {
		return x.Orderfile
	}
	return ""
}

func (x *DiffFormatting) GetSkipTo() string {
	if x != nil {
		return x.SkipTo
	}
	return ""
}

func (x *DiffFormatting) GetRotateTo() string {
	if x != nil {
		return x.RotateTo
	}
	return ""
}

func (x *DiffFormatting) GetReverse() OptBool {
	if x != nil {
		return x.Reverse
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetRelative() OptBool {
	if x != nil {
		return x.Relative
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *DiffFormatting) GetNoRelative() OptBool {
	if x != nil {
		return x.NoRelative
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetText() OptBool {
	if x != nil {
		return x.Text
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreCrAtEol() OptBool {
	if x != nil {
		return x.IgnoreCrAtEol
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreSpaceAtEol() OptBool {
	if x != nil {
		return x.IgnoreSpaceAtEol
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreSpaceChange() OptBool {
	if x != nil {
		return x.IgnoreSpaceChange
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreAllSpace() OptBool {
	if x != nil {
		return x.IgnoreAllSpace
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreBlankLines() OptBool {
	if x != nil {
		return x.IgnoreBlankLines
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreMatchingLines() []string {
	if x != nil {
		return x.IgnoreMatchingLines
	}
	return nil
}

func (x *DiffFormatting) GetInterHunkContext() *OptInt {
	if x != nil {
		return x.InterHunkContext
	}
	return nil
}

func (x *DiffFormatting) GetFunctionContext() OptBool {
	if x != nil {
		return x.FunctionContext
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetExitCode() OptBool {
	if x != nil {
		return x.ExitCode
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetQuiet() OptBool {
	if x != nil {
		return x.Quiet
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetExtDiff() OptBool {
	if x != nil {
		return x.ExtDiff
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetNoExtDiff() OptBool {
	if x != nil {
		return x.NoExtDiff
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetTextconv() OptBool {
	if x != nil {
		return x.Textconv
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreSubmodules() OptBool {
	if x != nil {
		return x.IgnoreSubmodules
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetIgnoreSubmodulesWhen() string {
	if x != nil {
		return x.IgnoreSubmodulesWhen
	}
	return ""
}

func (x *DiffFormatting) GetSrcPrefix() string {
	if x != nil {
		return x.SrcPrefix
	}
	return ""
}

func (x *DiffFormatting) GetDstPrefix() string {
	if x != nil {
		return x.DstPrefix
	}
	return ""
}

func (x *DiffFormatting) GetNoPrefix() OptBool {
	if x != nil {
		return x.NoPrefix
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetLinePrefix() string {
	if x != nil {
		return x.LinePrefix
	}
	return ""
}

func (x *DiffFormatting) GetItaInvisibleInIndex() OptBool {
	if x != nil {
		return x.ItaInvisibleInIndex
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

func (x *DiffFormatting) GetItaVisibleInIndex() OptBool {
	if x != nil {
		return x.ItaVisibleInIndex
	}
	return OptBool_OPT_BOOL_UNSPECIFIED
}

var File_flags_proto protoreflect.FileDescriptor

const file_flags_proto_rawDesc = "" +
	"\n" +
	"\vflags.proto\x12\vsubcommands\"\x96\x01\n" +
	"\bPathspec\x12\x1a\n" +
	"\bpathspec\x18\x01 \x03(\tR\bpathspec\x12,\n" +
	"\x12pathspec_from_file\x18\x02 \x01(\tR\x10pathspecFromFile\x12@\n" +
	"\x11pathspec_file_nul\x18\x03 \x01(\x0e2\x14.subcommands.OptBoolR\x0fpathspecFileNul\"\xd3\x01\n" +
	"\rMessageSource\x12\x18\n" +
	"\amessage\x18\x01 \x03(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12#\n" +
	"\rreuse_message\x18\x03 \x01(\tR\freuseMessage\x12%\n" +
	"\x0ereedit_message\x18\x04 \x01(\tR\rreeditMessage\x12\x16\n" +
	"\x06squash\x18\x05 \x01(\tR\x06squash\x12\x14\n" +
	"\x05fixup\x18\x06 \x01(\tR\x05fixup\x12\x1a\n" +
	"\btemplate\x18\a \x01(\tR\btemplate\"J\n" +
	"\aGpgSign\x12(\n" +
	"\x04sign\x18\x01 \x01(\x0e2\x14.subcommands.OptBoolR\x04sign\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\">\n" +
	"\x10IdentityOverride\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"8\n" +
	"\x06OptInt\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\xb4%\n" +
	"\x0eDiffFormatting\x12*\n" +
	"\x05patch\x18\x01 \x01(\x0e2\x14.subcommands.OptBoolR\x05patch\x12/\n" +
	"\bno_patch\x18\x02 \x01(\x0e2\x14.subcommands.OptBoolR\anoPatch\x12-\n" +
	"\aunified\x18\x03 \x01(\v2\x13.subcommands.OptIntR\aunified\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x120\n" +
	"\x14output_indicator_new\x18\x05 \x01(\tR\x12outputIndicatorNew\x120\n" +
	"\x14output_indicator_old\x18\x06 \x01(\tR\x12outputIndicatorOld\x128\n" +
	"\x18output_indicator_context\x18\a \x01(\tR\x16outputIndicatorContext\x12&\n" +
	"\x03raw\x18\b \x01(\x0e2\x14.subcommands.OptBoolR\x03raw\x12:\n" +
	"\x0epatch_with_raw\x18\t \x01(\x0e2\x14.subcommands.OptBoolR\fpatchWithRaw\x12?\n" +
	"\x10indent_heuristic\x18\n" +
	" \x01(\x0e2\x14.subcommands.OptBoolR\x0findentHeuristic\x12.\n" +
	"\aminimal\x18\v \x01(\x0e2\x14.subcommands.OptBoolR\aminimal\x120\n" +
	"\bpatience\x18\f \x01(\x0e2\x14.subcommands.OptBoolR\bpatience\x122\n" +
	"\thistogram\x18\r \x01(\x0e2\x14.subcommands.OptBoolR\thistogram\x12\x1a\n" +
	"\banchored\x18\x0e \x03(\tR\banchored\x12%\n" +
	"\x0ediff_algorithm\x18\x0f \x01(\tR\rdiffAlgorithm\x12(\n" +
	"\x04stat\x18\x10 \x01(\x0e2\x14.subcommands.OptBoolR\x04stat\x12\x1b\n" +
	"\tstat_spec\x18\x11 \x01(\tR\bstatSpec\x122\n" +
	"\n" +
	"stat_width\x18\x12 \x01(\v2\x13.subcommands.OptIntR\tstatWidth\x12;\n" +
	"\x0fstat_name_width\x18\x13 \x01(\v2\x13.subcommands.OptIntR\rstatNameWidth\x122\n" +
	"\n" +
	"stat_count\x18\x14 \x01(\v2\x13.subcommands.OptIntR\tstatCount\x12=\n" +
	"\x0fcompact_summary\x18\x15 \x01(\x0e2\x14.subcommands.OptBoolR\x0ecompactSummary\x12.\n" +
	"\anumstat\x18\x16 \x01(\x0e2\x14.subcommands.OptBoolR\anumstat\x122\n" +
	"\tshortstat\x18\x17 \x01(\x0e2\x14.subcommands.OptBoolR\tshortstat\x12.\n" +
	"\adirstat\x18\x18 \x01(\x0e2\x14.subcommands.OptBoolR\adirstat\x12%\n" +
	"\x0edirstat_params\x18\x19 \x01(\tR\rdirstatParams\x124\n" +
	"\n" +
	"cumulative\x18\x1a \x01(\x0e2\x14.subcommands.OptBoolR\n" +
	"cumulative\x12<\n" +
	"\x0fdirstat_by_file\x18\x1b \x01(\x0e2\x14.subcommands.OptBoolR\rdirstatByFile\x123\n" +
	"\x16dirstat_by_file_params\x18\x1c \x01(\tR\x13dirstatByFileParams\x12.\n" +
	"\asummary\x18\x1d \x01(\x0e2\x14.subcommands.OptBoolR\asummary\x12<\n" +
	"\x0fpatch_with_stat\x18\x1e \x01(\x0e2\x14.subcommands.OptBoolR\rpatchWithStat\x12\"\n" +
	"\x01z\x18\x1f \x01(\x0e2\x14.subcommands.OptBoolR\x01z\x121\n" +
	"\tname_only\x18  \x01(\x0e2\x14.subcommands.OptBoolR\bnameOnly\x125\n" +
	"\vname_status\x18! \x01(\x0e2\x14.subcommands.OptBoolR\n" +
	"nameStatus\x122\n" +
	"\tsubmodule\x18\" \x01(\x0e2\x14.subcommands.OptBoolR\tsubmodule\x12)\n" +
	"\x10submodule_format\x18# \x01(\tR\x0fsubmoduleFormat\x12,\n" +
	"\x05color\x18$ \x01(\x0e2\x16.subcommands.ColorWhenR\x05color\x123\n" +
	"\n" +
	"color_flag\x18% \x01(\x0e2\x14.subcommands.OptBoolR\tcolorFlag\x12/\n" +
	"\bno_color\x18& \x01(\x0e2\x14.subcommands.OptBoolR\anoColor\x125\n" +
	"\vcolor_moved\x18' \x01(\x0e2\x14.subcommands.OptBoolR\n" +
	"colorMoved\x12(\n" +
	"\x10color_moved_mode\x18( \x01(\tR\x0ecolorMovedMode\x12:\n" +
	"\x0eno_color_moved\x18) \x01(\x0e2\x14.subcommands.OptBoolR\fnoColorMoved\x12$\n" +
	"\x0ecolor_moved_ws\x18* \x01(\tR\fcolorMovedWs\x12?\n" +
	"\x11no_color_moved_ws\x18+ \x01(\x0e2\x14.subcommands.OptBoolR\x0enoColorMovedWs\x121\n" +
	"\tword_diff\x18, \x01(\x0e2\x14.subcommands.OptBoolR\bwordDiff\x12$\n" +
	"\x0eword_diff_mode\x18- \x01(\tR\fwordDiffMode\x12&\n" +
	"\x0fword_diff_regex\x18. \x01(\tR\rwordDiffRegex\x125\n" +
	"\vcolor_words\x18/ \x01(\x0e2\x14.subcommands.OptBoolR\n" +
	"colorWords\x12*\n" +
	"\x11color_words_regex\x180 \x01(\tR\x0fcolorWordsRegex\x123\n" +
	"\n" +
	"no_renames\x181 \x01(\x0e2\x14.subcommands.OptBoolR\tnoRenames\x127\n" +
	"\frename_empty\x182 \x01(\x0e2\x14.subcommands.OptBoolR\vrenameEmpty\x12*\n" +
	"\x05check\x183 \x01(\x0e2\x14.subcommands.OptBoolR\x05check\x12,\n" +
	"\x12ws_error_highlight\x184 \x01(\tR\x10wsErrorHighlight\x123\n" +
	"\n" +
	"full_index\x185 \x01(\x0e2\x14.subcommands.OptBoolR\tfullIndex\x12,\n" +
	"\x06binary\x186 \x01(\x0e2\x14.subcommands.OptBoolR\x06binary\x12+\n" +
	"\x06abbrev\x187 \x01(\v2\x13.subcommands.OptIntR\x06abbrev\x121\n" +
	"\tno_abbrev\x188 \x01(\x0e2\x14.subcommands.OptBoolR\bnoAbbrev\x12%\n" +
	"\x0ebreak_rewrites\x189 \x01(\tR\rbreakRewrites\x12!\n" +
	"\ffind_renames\x18: \x01(\tR\vfindRenames\x12\x1f\n" +
	"\vfind_copies\x18; \x01(\tR\n" +
	"findCopies\x12B\n" +
	"\x12find_copies_harder\x18< \x01(\x0e2\x14.subcommands.OptBoolR\x10findCopiesHarder\x12E\n" +
	"\x13irreversible_delete\x18= \x01(\x0e2\x14.subcommands.OptBoolR\x12irreversibleDelete\x126\n" +
	"\frename_limit\x18> \x01(\v2\x13.subcommands.OptIntR\vrenameLimit\x12\x1f\n" +
	"\vdiff_filter\x18? \x01(\tR\n" +
	"diffFilter\x12\x1b\n" +
	"\tpickaxe_s\x18@ \x01(\tR\bpickaxeS\x12\x1b\n" +
	"\tpickaxe_g\x18A \x01(\tR\bpickaxeG\x12\x1f\n" +
	"\vfind_object\x18B \x01(\tR\n" +
	"findObject\x125\n" +
	"\vpickaxe_all\x18C \x01(\x0e2\x14.subcommands.OptBoolR\n" +
	"pickaxeAll\x129\n" +
	"\rpickaxe_regex\x18D \x01(\x0e2\x14.subcommands.OptBoolR\fpickaxeRegex\x12\x1c\n" +
	"\torderfile\x18E \x01(\tR\torderfile\x12\x17\n" +
	"\askip_to\x18F \x01(\tR\x06skipTo\x12\x1b\n" +
	"\trotate_to\x18G \x01(\tR\brotateTo\x12.\n" +
	"\areverse\x18H \x01(\x0e2\x14.subcommands.OptBoolR\areverse\x120\n" +
	"\brelative\x18I \x01(\x0e2\x14.subcommands.OptBoolR\brelative\x12#\n" +
	"\rrelative_path\x18J \x01(\tR\frelativePath\x125\n" +
	"\vno_relative\x18K \x01(\x0e2\x14.subcommands.OptBoolR\n" +
	"noRelative\x12(\n" +
	"\x04text\x18L \x01(\x0e2\x14.subcommands.OptBoolR\x04text\x12=\n" +
	"\x10ignore_cr_at_eol\x18M \x01(\x0e2\x14.subcommands.OptBoolR\rignoreCrAtEol\x12C\n" +
	"\x13ignore_space_at_eol\x18N \x01(\x0e2\x14.subcommands.OptBoolR\x10ignoreSpaceAtEol\x12D\n" +
	"\x13ignore_space_change\x18O \x01(\x0e2\x14.subcommands.OptBoolR\x11ignoreSpaceChange\x12>\n" +
	"\x10ignore_all_space\x18P \x01(\x0e2\x14.subcommands.OptBoolR\x0eignoreAllSpace\x12B\n" +
	"\x12ignore_blank_lines\x18Q \x01(\x0e2\x14.subcommands.OptBoolR\x10ignoreBlankLines\x122\n" +
	"\x15ignore_matching_lines\x18R \x03(\tR\x13ignoreMatchingLines\x12A\n" +
	"\x12inter_hunk_context\x18S \x01(\v2\x13.subcommands.OptIntR\x10interHunkContext\x12?\n" +
	"\x10function_context\x18T \x01(\x0e2\x14.subcommands.OptBoolR\x0ffunctionContext\x121\n" +
	"\texit_code\x18U \x01(\x0e2\x14.subcommands.OptBoolR\bexitCode\x12*\n" +
	"\x05quiet\x18V \x01(\x0e2\x14.subcommands.OptBoolR\x05quiet\x12/\n" +
	"\bext_diff\x18W \x01(\x0e2\x14.subcommands.OptBoolR\aextDiff\x124\n" +
	"\vno_ext_diff\x18X \x01(\x0e2\x14.subcommands.OptBoolR\tnoExtDiff\x120\n" +
	"\btextconv\x18Y \x01(\x0e2\x14.subcommands.OptBoolR\btextconv\x12A\n" +
	"\x11ignore_submodules\x18Z \x01(\x0e2\x14.subcommands.OptBoolR\x10ignoreSubmodules\x124\n" +
	"\x16ignore_submodules_when\x18[ \x01(\tR\x14ignoreSubmodulesWhen\x12\x1d\n" +
	"\n" +
	"src_prefix\x18\\ \x01(\tR\tsrcPrefix\x12\x1d\n" +
	"\n" +
	"dst_prefix\x18] \x01(\tR\tdstPrefix\x121\n" +
	"\tno_prefix\x18^ \x01(\x0e2\x14.subcommands.OptBoolR\bnoPrefix\x12\x1f\n" +
	"\vline_prefix\x18_ \x01(\tR\n" +
	"linePrefix\x12I\n" +
	"\x16ita_invisible_in_index\x18` \x01(\x0e2\x14.subcommands.OptBoolR\x13itaInvisibleInIndex\x12E\n" +
	"\x14ita_visible_in_index\x18a \x01(\x0e2\x14.subcommands.OptBoolR\x11itaVisibleInIndex*J\n" +
	"\aOptBool\x12\x18\n" +
	"\x14OPT_BOOL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOPT_BOOL_TRUE\x10\x01\x12\x12\n" +
	"\x0eOPT_BOOL_FALSE\x10\x02*r\n" +
	"\vFastForward\x12\x1c\n" +
	"\x18FAST_FORWARD_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FAST_FORWARD_ALLOW\x10\x01\x12\x16\n" +
	"\x12FAST_FORWARD_NEVER\x10\x02\x12\x15\n" +
	"\x11FAST_FORWARD_ONLY\x10\x03*j\n" +
	"\x0fChmodExecutable\x12 \n" +
	"\x1cCHMOD_EXECUTABLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CHMOD_EXECUTABLE_ADD\x10\x01\x12\x1b\n" +
	"\x17CHMOD_EXECUTABLE_REMOVE\x10\x02*\x96\x01\n" +
	"\x12UntrackedFilesMode\x12$\n" +
	" UNTRACKED_FILES_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17UNTRACKED_FILES_MODE_NO\x10\x01\x12\x1f\n" +
	"\x1bUNTRACKED_FILES_MODE_NORMAL\x10\x02\x12\x1c\n" +
	"\x18UNTRACKED_FILES_MODE_ALL\x10\x03*y\n" +
	"\vIgnoredMode\x12\x1c\n" +
	"\x18IGNORED_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18IGNORED_MODE_TRADITIONAL\x10\x01\x12\x19\n" +
	"\x15IGNORED_MODE_MATCHING\x10\x02\x12\x13\n" +
	"\x0fIGNORED_MODE_NO\x10\x03*\x9e\x01\n" +
	"\fStatusFormat\x12\x1d\n" +
	"\x19STATUS_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STATUS_FORMAT_LONG\x10\x01\x12\x17\n" +
	"\x13STATUS_FORMAT_SHORT\x10\x02\x12\x1e\n" +
	"\x1aSTATUS_FORMAT_PORCELAIN_V1\x10\x03\x12\x1e\n" +
	"\x1aSTATUS_FORMAT_PORCELAIN_V2\x10\x04*o\n" +
	"\bDecorate\x12\x18\n" +
	"\x14DECORATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECORATE_SHORT\x10\x01\x12\x11\n" +
	"\rDECORATE_FULL\x10\x02\x12\x11\n" +
	"\rDECORATE_AUTO\x10\x03\x12\x0f\n" +
	"\vDECORATE_NO\x10\x04*i\n" +
	"\tColorWhen\x12\x1a\n" +
	"\x16COLOR_WHEN_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COLOR_WHEN_ALWAYS\x10\x01\x12\x14\n" +
	"\x10COLOR_WHEN_NEVER\x10\x02\x12\x13\n" +
	"\x0fCOLOR_WHEN_AUTO\x10\x03*\x8b\x01\n" +
	"\x0fBranchTrackMode\x12!\n" +
	"\x1dBRANCH_TRACK_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BRANCH_TRACK_MODE_DIRECT\x10\x01\x12\x1d\n" +
	"\x19BRANCH_TRACK_MODE_INHERIT\x10\x02\x12\x18\n" +
	"\x14BRANCH_TRACK_MODE_NO\x10\x03*\xcb\x01\n" +
	"\x11RecurseSubmodules\x12\"\n" +
	"\x1eRECURSE_SUBMODULES_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RECURSE_SUBMODULES_NO\x10\x01\x12\x1a\n" +
	"\x16RECURSE_SUBMODULES_YES\x10\x02\x12 \n" +
	"\x1cRECURSE_SUBMODULES_ON_DEMAND\x10\x03\x12\x1c\n" +
	"\x18RECURSE_SUBMODULES_CHECK\x10\x04\x12\x1b\n" +
	"\x17RECURSE_SUBMODULES_ONLY\x10\x05B)Z'github.com/accretional/proto-repo/genpbb\x06proto3"

var (
	file_flags_proto_rawDescOnce sync.Once
	file_flags_proto_rawDescData []byte
)

func file_flags_proto_rawDescGZIP() []byte {
	file_flags_proto_rawDescOnce.Do(func() {
		file_flags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flags_proto_rawDesc), len(file_flags_proto_rawDesc)))
	})
	return file_flags_proto_rawDescData
}

var file_flags_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_flags_proto_goTypes = []any{
	(OptBool)(0),             // 0: subcommands.OptBool
	(FastForward)(0),         // 1: subcommands.FastForward
	(ChmodExecutable)(0),     // 2: subcommands.ChmodExecutable
	(UntrackedFilesMode)(0),  // 3: subcommands.UntrackedFilesMode
	(IgnoredMode)(0),         // 4: subcommands.IgnoredMode
	(StatusFormat)(0),        // 5: subcommands.StatusFormat
	(Decorate)(0),            // 6: subcommands.Decorate
	(ColorWhen)(0),           // 7: subcommands.ColorWhen
	(BranchTrackMode)(0),     // 8: subcommands.BranchTrackMode
	(RecurseSubmodules)(0),   // 9: subcommands.RecurseSubmodules
	(*Pathspec)(nil),         // 10: subcommands.Pathspec
	(*MessageSource)(nil),    // 11: subcommands.MessageSource
	(*GpgSign)(nil),          // 12: subcommands.GpgSign
	(*IdentityOverride)(nil), // 13: subcommands.IdentityOverride
	(*OptInt)(nil),           // 14: subcommands.OptInt
	(*DiffFormatting)(nil),   // 15: subcommands.DiffFormatting
}
var file_flags_proto_depIdxs = []int32{
	0,  // 0: subcommands.Pathspec.pathspec_file_nul:type_name -> subcommands.OptBool
	0,  // 1: subcommands.GpgSign.sign:type_name -> subcommands.OptBool
	0,  // 2: subcommands.DiffFormatting.patch:type_name -> subcommands.OptBool
	0,  // 3: subcommands.DiffFormatting.no_patch:type_name -> subcommands.OptBool
	14, // 4: subcommands.DiffFormatting.unified:type_name -> subcommands.OptInt
	0,  // 5: subcommands.DiffFormatting.raw:type_name -> subcommands.OptBool
	0,  // 6: subcommands.DiffFormatting.patch_with_raw:type_name -> subcommands.OptBool
	0,  // 7: subcommands.DiffFormatting.indent_heuristic:type_name -> subcommands.OptBool
	0,  // 8: subcommands.DiffFormatting.minimal:type_name -> subcommands.OptBool
	0,  // 9: subcommands.DiffFormatting.patience:type_name -> subcommands.OptBool
	0,  // 10: subcommands.DiffFormatting.histogram:type_name -> subcommands.OptBool
	0,  // 11: subcommands.DiffFormatting.stat:type_name -> subcommands.OptBool
	14, // 12: subcommands.DiffFormatting.stat_width:type_name -> subcommands.OptInt
	14, // 13: subcommands.DiffFormatting.stat_name_width:type_name -> subcommands.OptInt
	14, // 14: subcommands.DiffFormatting.stat_count:type_name -> subcommands.OptInt
	0,  // 15: subcommands.DiffFormatting.compact_summary:type_name -> subcommands.OptBool
	0,  // 16: subcommands.DiffFormatting.numstat:type_name -> subcommands.OptBool
	0,  // 17: subcommands.DiffFormatting.shortstat:type_name -> subcommands.OptBool
	0,  // 18: subcommands.DiffFormatting.dirstat:type_name -> subcommands.OptBool
	0,  // 19: subcommands.DiffFormatting.cumulative:type_name -> subcommands.OptBool
	0,  // 20: subcommands.DiffFormatting.dirstat_by_file:type_name -> subcommands.OptBool
	0,  // 21: subcommands.DiffFormatting.summary:type_name -> subcommands.OptBool
	0,  // 22: subcommands.DiffFormatting.patch_with_stat:type_name -> subcommands.OptBool
	0,  // 23: subcommands.DiffFormatting.z:type_name -> subcommands.OptBool
	0,  // 24: subcommands.DiffFormatting.name_only:type_name -> subcommands.OptBool
	0,  // 25: subcommands.DiffFormatting.name_status:type_name -> subcommands.OptBool
	0,  // 26: subcommands.DiffFormatting.submodule:type_name -> subcommands.OptBool
	7,  // 27: subcommands.DiffFormatting.color:type_name -> subcommands.ColorWhen
	0,  // 28: subcommands.DiffFormatting.color_flag:type_name -> subcommands.OptBool
	0,  // 29: subcommands.DiffFormatting.no_color:type_name -> subcommands.OptBool
	0,  // 30: subcommands.DiffFormatting.color_moved:type_name -> subcommands.OptBool
	0,  // 31: subcommands.DiffFormatting.no_color_moved:type_name -> subcommands.OptBool
	0,  // 32: subcommands.DiffFormatting.no_color_moved_ws:type_name -> subcommands.OptBool
	0,  // 33: subcommands.DiffFormatting.word_diff:type_name -> subcommands.OptBool
	0,  // 34: subcommands.DiffFormatting.color_words:type_name -> subcommands.OptBool
	0,  // 35: subcommands.DiffFormatting.no_renames:type_name -> subcommands.OptBool
	0,  // 36: subcommands.DiffFormatting.rename_empty:type_name -> subcommands.OptBool
	0,  // 37: subcommands.DiffFormatting.check:type_name -> subcommands.OptBool
	0,  // 38: subcommands.DiffFormatting.full_index:type_name -> subcommands.OptBool
	0,  // 39: subcommands.DiffFormatting.binary:type_name -> subcommands.OptBool
	14, // 40: subcommands.DiffFormatting.abbrev:type_name -> subcommands.OptInt
	0,  // 41: subcommands.DiffFormatting.no_abbrev:type_name -> subcommands.OptBool
	0,  // 42: subcommands.DiffFormatting.find_copies_harder:type_name -> subcommands.OptBool
	0,  // 43: subcommands.DiffFormatting.irreversible_delete:type_name -> subcommands.OptBool
	14, // 44: subcommands.DiffFormatting.rename_limit:type_name -> subcommands.OptInt
	0,  // 45: subcommands.DiffFormatting.pickaxe_all:type_name -> subcommands.OptBool
	0,  // 46: subcommands.DiffFormatting.pickaxe_regex:type_name -> subcommands.OptBool
	0,  // 47: subcommands.DiffFormatting.reverse:type_name -> subcommands.OptBool
	0,  // 48: subcommands.DiffFormatting.relative:type_name -> subcommands.OptBool
	0,  // 49: subcommands.DiffFormatting.no_relative:type_name -> subcommands.OptBool
	0,  // 50: subcommands.DiffFormatting.text:type_name -> subcommands.OptBool
	0,  // 51: subcommands.DiffFormatting.ignore_cr_at_eol:type_name -> subcommands.OptBool
	0,  // 52: subcommands.DiffFormatting.ignore_space_at_eol:type_name -> subcommands.OptBool
	0,  // 53: subcommands.DiffFormatting.ignore_space_change:type_name -> subcommands.OptBool
	0,  // 54: subcommands.DiffFormatting.ignore_all_space:type_name -> subcommands.OptBool
	0,  // 55: subcommands.DiffFormatting.ignore_blank_lines:type_name -> subcommands.OptBool
	14, // 56: subcommands.DiffFormatting.inter_hunk_context:type_name -> subcommands.OptInt
	0,  // 57: subcommands.DiffFormatting.function_context:type_name -> subcommands.OptBool
	0,  // 58: subcommands.DiffFormatting.exit_code:type_name -> subcommands.OptBool
	0,  // 59: subcommands.DiffFormatting.quiet:type_name -> subcommands.OptBool
	0,  // 60: subcommands.DiffFormatting.ext_diff:type_name -> subcommands.OptBool
	0,  // 61: subcommands.DiffFormatting.no_ext_diff:type_name -> subcommands.OptBool
	0,  // 62: subcommands.DiffFormatting.textconv:type_name -> subcommands.OptBool
	0,  // 63: subcommands.DiffFormatting.ignore_submodules:type_name -> subcommands.OptBool
	0,  // 64: subcommands.DiffFormatting.no_prefix:type_name -> subcommands.OptBool
	0,  // 65: subcommands.DiffFormatting.ita_invisible_in_index:type_name -> subcommands.OptBool
	0,  // 66: subcommands.DiffFormatting.ita_visible_in_index:type_name -> subcommands.OptBool
	67, // [67:67] is the sub-list for method output_type
	67, // [67:67] is the sub-list for method input_type
	67, // [67:67] is the sub-list for extension type_name
	67, // [67:67] is the sub-list for extension extendee
	0,  // [0:67] is the sub-list for field type_name
}

func init() { file_flags_proto_init() }
func file_flags_proto_init() {
	if File_flags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flags_proto_rawDesc), len(file_flags_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flags_proto_goTypes,
		DependencyIndexes: file_flags_proto_depIdxs,
		EnumInfos:         file_flags_proto_enumTypes,
		MessageInfos:      file_flags_proto_msgTypes,
	}.Build()
	File_flags_proto = out.File
	file_flags_proto_goTypes = nil
	file_flags_proto_depIdxs = nil
}
