// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: repo.proto

package genpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GithubRepo identifies a repository on GitHub.
type GithubRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubRepo) Reset() {
	*x = GithubRepo{}
	mi := &file_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubRepo) ProtoMessage() {}

func (x *GithubRepo) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubRepo.ProtoReflect.Descriptor instead.
func (*GithubRepo) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{0}
}

func (x *GithubRepo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GithubRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RepoSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*RepoSource_Uri
	//	*RepoSource_Gh
	//	*RepoSource_Path
	Source        isRepoSource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoSource) Reset() {
	*x = RepoSource{}
	mi := &file_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoSource) ProtoMessage() {}

func (x *RepoSource) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoSource.ProtoReflect.Descriptor instead.
func (*RepoSource) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{1}
}

func (x *RepoSource) GetSource() isRepoSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RepoSource) GetUri() string {
	if x != nil {
		if x, ok := x.Source.(*RepoSource_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *RepoSource) GetGh() *GithubRepo {
	if x != nil {
		if x, ok := x.Source.(*RepoSource_Gh); ok {
			return x.Gh
		}
	}
	return nil
}

func (x *RepoSource) GetPath() *RepoPath {
	if x != nil {
		if x, ok := x.Source.(*RepoSource_Path); ok {
			return x.Path
		}
	}
	return nil
}

type isRepoSource_Source interface {
	isRepoSource_Source()
}

type RepoSource_Uri struct {
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3,oneof"`
}

type RepoSource_Gh struct {
	Gh *GithubRepo `protobuf:"bytes,2,opt,name=gh,proto3,oneof"`
}

type RepoSource_Path struct {
	Path *RepoPath `protobuf:"bytes,3,opt,name=path,proto3,oneof"`
}

func (*RepoSource_Uri) isRepoSource_Source() {}

func (*RepoSource_Gh) isRepoSource_Source() {}

func (*RepoSource_Path) isRepoSource_Source() {}

// Repo identifies a source code repository from any supported host.
type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *RepoSource            `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{2}
}

func (x *Repo) GetSource() *RepoSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Repo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Repo) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

// RepoList is a collection of repositories.
type RepoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoList) Reset() {
	*x = RepoList{}
	mi := &file_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoList) ProtoMessage() {}

func (x *RepoList) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoList.ProtoReflect.Descriptor instead.
func (*RepoList) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{3}
}

func (x *RepoList) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type RepoPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoPath) Reset() {
	*x = RepoPath{}
	mi := &file_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoPath) ProtoMessage() {}

func (x *RepoPath) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoPath.ProtoReflect.Descriptor instead.
func (*RepoPath) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{4}
}

func (x *RepoPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RepoLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          []string               `protobuf:"bytes,1,rep,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoLogs) Reset() {
	*x = RepoLogs{}
	mi := &file_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoLogs) ProtoMessage() {}

func (x *RepoLogs) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoLogs.ProtoReflect.Descriptor instead.
func (*RepoLogs) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{5}
}

func (x *RepoLogs) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

type RepoMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repo                  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Stdout        *RepoLogs              `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        *RepoLogs              `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Errs          []string               `protobuf:"bytes,4,rep,name=errs,proto3" json:"errs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoMsg) Reset() {
	*x = RepoMsg{}
	mi := &file_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoMsg) ProtoMessage() {}

func (x *RepoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoMsg.ProtoReflect.Descriptor instead.
func (*RepoMsg) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{6}
}

func (x *RepoMsg) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *RepoMsg) GetStdout() *RepoLogs {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RepoMsg) GetStderr() *RepoLogs {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RepoMsg) GetErrs() []string {
	if x != nil {
		return x.Errs
	}
	return nil
}

type MultiRepoZip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         *RepoList              `protobuf:"bytes,1,opt,name=repos,proto3" json:"repos,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"zigzag64,3,opt,name=size,proto3" json:"size,omitempty"`
	NumFiles      int32                  `protobuf:"varint,4,opt,name=num_files,json=numFiles,proto3" json:"num_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRepoZip) Reset() {
	*x = MultiRepoZip{}
	mi := &file_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRepoZip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRepoZip) ProtoMessage() {}

func (x *MultiRepoZip) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRepoZip.ProtoReflect.Descriptor instead.
func (*MultiRepoZip) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{7}
}

func (x *MultiRepoZip) GetRepos() *RepoList {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *MultiRepoZip) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MultiRepoZip) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MultiRepoZip) GetNumFiles() int32 {
	if x != nil {
		return x.NumFiles
	}
	return 0
}

var File_repo_proto protoreflect.FileDescriptor

const file_repo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"repo.proto\x12\x04repo\"6\n" +
	"\n" +
	"GithubRepo\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"t\n" +
	"\n" +
	"RepoSource\x12\x12\n" +
	"\x03uri\x18\x01 \x01(\tH\x00R\x03uri\x12\"\n" +
	"\x02gh\x18\x02 \x01(\v2\x10.repo.GithubRepoH\x00R\x02gh\x12$\n" +
	"\x04path\x18\x03 \x01(\v2\x0e.repo.RepoPathH\x00R\x04pathB\b\n" +
	"\x06source\"`\n" +
	"\x04Repo\x12(\n" +
	"\x06source\x18\x01 \x01(\v2\x10.repo.RepoSourceR\x06source\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\",\n" +
	"\bRepoList\x12 \n" +
	"\x05repos\x18\x01 \x03(\v2\n" +
	".repo.RepoR\x05repos\"\x1e\n" +
	"\bRepoPath\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1e\n" +
	"\bRepoLogs\x12\x12\n" +
	"\x04line\x18\x01 \x03(\tR\x04line\"\x8d\x01\n" +
	"\aRepoMsg\x12\x1e\n" +
	"\x04repo\x18\x01 \x01(\v2\n" +
	".repo.RepoR\x04repo\x12&\n" +
	"\x06stdout\x18\x02 \x01(\v2\x0e.repo.RepoLogsR\x06stdout\x12&\n" +
	"\x06stderr\x18\x03 \x01(\v2\x0e.repo.RepoLogsR\x06stderr\x12\x12\n" +
	"\x04errs\x18\x04 \x03(\tR\x04errs\"y\n" +
	"\fMultiRepoZip\x12$\n" +
	"\x05repos\x18\x01 \x01(\v2\x0e.repo.RepoListR\x05repos\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x12R\x04size\x12\x1b\n" +
	"\tnum_files\x18\x04 \x01(\x05R\bnumFiles2\xe0\x01\n" +
	"\bImporter\x12+\n" +
	"\bDownload\x12\x0e.repo.RepoList\x1a\r.repo.RepoMsg0\x01\x12(\n" +
	"\x05Clone\x12\x0e.repo.RepoList\x1a\r.repo.RepoMsg0\x01\x12)\n" +
	"\x05Where\x12\x0e.repo.RepoList\x1a\x0e.repo.RepoPath0\x01\x12'\n" +
	"\x04Pull\x12\x0e.repo.RepoList\x1a\r.repo.RepoMsg0\x01\x12)\n" +
	"\x03Zip\x12\x0e.repo.RepoList\x1a\x12.repo.MultiRepoZipB)Z'github.com/accretional/proto-repo/genpbb\x06proto3"

var (
	file_repo_proto_rawDescOnce sync.Once
	file_repo_proto_rawDescData []byte
)

func file_repo_proto_rawDescGZIP() []byte {
	file_repo_proto_rawDescOnce.Do(func() {
		file_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)))
	})
	return file_repo_proto_rawDescData
}

var file_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_repo_proto_goTypes = []any{
	(*GithubRepo)(nil),   // 0: repo.GithubRepo
	(*RepoSource)(nil),   // 1: repo.RepoSource
	(*Repo)(nil),         // 2: repo.Repo
	(*RepoList)(nil),     // 3: repo.RepoList
	(*RepoPath)(nil),     // 4: repo.RepoPath
	(*RepoLogs)(nil),     // 5: repo.RepoLogs
	(*RepoMsg)(nil),      // 6: repo.RepoMsg
	(*MultiRepoZip)(nil), // 7: repo.MultiRepoZip
}
var file_repo_proto_depIdxs = []int32{
	0,  // 0: repo.RepoSource.gh:type_name -> repo.GithubRepo
	4,  // 1: repo.RepoSource.path:type_name -> repo.RepoPath
	1,  // 2: repo.Repo.source:type_name -> repo.RepoSource
	2,  // 3: repo.RepoList.repos:type_name -> repo.Repo
	2,  // 4: repo.RepoMsg.repo:type_name -> repo.Repo
	5,  // 5: repo.RepoMsg.stdout:type_name -> repo.RepoLogs
	5,  // 6: repo.RepoMsg.stderr:type_name -> repo.RepoLogs
	3,  // 7: repo.MultiRepoZip.repos:type_name -> repo.RepoList
	3,  // 8: repo.Importer.Download:input_type -> repo.RepoList
	3,  // 9: repo.Importer.Clone:input_type -> repo.RepoList
	3,  // 10: repo.Importer.Where:input_type -> repo.RepoList
	3,  // 11: repo.Importer.Pull:input_type -> repo.RepoList
	3,  // 12: repo.Importer.Zip:input_type -> repo.RepoList
	6,  // 13: repo.Importer.Download:output_type -> repo.RepoMsg
	6,  // 14: repo.Importer.Clone:output_type -> repo.RepoMsg
	4,  // 15: repo.Importer.Where:output_type -> repo.RepoPath
	6,  // 16: repo.Importer.Pull:output_type -> repo.RepoMsg
	7,  // 17: repo.Importer.Zip:output_type -> repo.MultiRepoZip
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_repo_proto_init() }
func file_repo_proto_init() {
	if File_repo_proto != nil {
		return
	}
	file_repo_proto_msgTypes[1].OneofWrappers = []any{
		(*RepoSource_Uri)(nil),
		(*RepoSource_Gh)(nil),
		(*RepoSource_Path)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repo_proto_goTypes,
		DependencyIndexes: file_repo_proto_depIdxs,
		MessageInfos:      file_repo_proto_msgTypes,
	}.Build()
	File_repo_proto = out.File
	file_repo_proto_goTypes = nil
	file_repo_proto_depIdxs = nil
}
