// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: repo.proto

package genpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Importer_Download_FullMethodName = "/repo.Importer/Download"
	Importer_Clone_FullMethodName    = "/repo.Importer/Clone"
	Importer_Where_FullMethodName    = "/repo.Importer/Where"
	Importer_Pull_FullMethodName     = "/repo.Importer/Pull"
	Importer_Zip_FullMethodName      = "/repo.Importer/Zip"
)

// ImporterClient is the client API for Importer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImporterClient interface {
	// Local URI by default
	Download(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoMsg], error)
	Clone(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoMsg], error)
	Where(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoPath], error)
	Pull(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoMsg], error)
	Zip(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (*MultiRepoZip, error)
}

type importerClient struct {
	cc grpc.ClientConnInterface
}

func NewImporterClient(cc grpc.ClientConnInterface) ImporterClient {
	return &importerClient{cc}
}

func (c *importerClient) Download(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Importer_ServiceDesc.Streams[0], Importer_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepoList, RepoMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_DownloadClient = grpc.ServerStreamingClient[RepoMsg]

func (c *importerClient) Clone(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Importer_ServiceDesc.Streams[1], Importer_Clone_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepoList, RepoMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_CloneClient = grpc.ServerStreamingClient[RepoMsg]

func (c *importerClient) Where(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoPath], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Importer_ServiceDesc.Streams[2], Importer_Where_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepoList, RepoPath]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_WhereClient = grpc.ServerStreamingClient[RepoPath]

func (c *importerClient) Pull(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Importer_ServiceDesc.Streams[3], Importer_Pull_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepoList, RepoMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_PullClient = grpc.ServerStreamingClient[RepoMsg]

func (c *importerClient) Zip(ctx context.Context, in *RepoList, opts ...grpc.CallOption) (*MultiRepoZip, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiRepoZip)
	err := c.cc.Invoke(ctx, Importer_Zip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImporterServer is the server API for Importer service.
// All implementations must embed UnimplementedImporterServer
// for forward compatibility.
type ImporterServer interface {
	// Local URI by default
	Download(*RepoList, grpc.ServerStreamingServer[RepoMsg]) error
	Clone(*RepoList, grpc.ServerStreamingServer[RepoMsg]) error
	Where(*RepoList, grpc.ServerStreamingServer[RepoPath]) error
	Pull(*RepoList, grpc.ServerStreamingServer[RepoMsg]) error
	Zip(context.Context, *RepoList) (*MultiRepoZip, error)
	mustEmbedUnimplementedImporterServer()
}

// UnimplementedImporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImporterServer struct{}

func (UnimplementedImporterServer) Download(*RepoList, grpc.ServerStreamingServer[RepoMsg]) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedImporterServer) Clone(*RepoList, grpc.ServerStreamingServer[RepoMsg]) error {
	return status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedImporterServer) Where(*RepoList, grpc.ServerStreamingServer[RepoPath]) error {
	return status.Errorf(codes.Unimplemented, "method Where not implemented")
}
func (UnimplementedImporterServer) Pull(*RepoList, grpc.ServerStreamingServer[RepoMsg]) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedImporterServer) Zip(context.Context, *RepoList) (*MultiRepoZip, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Zip not implemented")
}
func (UnimplementedImporterServer) mustEmbedUnimplementedImporterServer() {}
func (UnimplementedImporterServer) testEmbeddedByValue()                  {}

// UnsafeImporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImporterServer will
// result in compilation errors.
type UnsafeImporterServer interface {
	mustEmbedUnimplementedImporterServer()
}

func RegisterImporterServer(s grpc.ServiceRegistrar, srv ImporterServer) {
	// If the following call pancis, it indicates UnimplementedImporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Importer_ServiceDesc, srv)
}

func _Importer_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepoList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImporterServer).Download(m, &grpc.GenericServerStream[RepoList, RepoMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_DownloadServer = grpc.ServerStreamingServer[RepoMsg]

func _Importer_Clone_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepoList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImporterServer).Clone(m, &grpc.GenericServerStream[RepoList, RepoMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_CloneServer = grpc.ServerStreamingServer[RepoMsg]

func _Importer_Where_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepoList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImporterServer).Where(m, &grpc.GenericServerStream[RepoList, RepoPath]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_WhereServer = grpc.ServerStreamingServer[RepoPath]

func _Importer_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepoList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImporterServer).Pull(m, &grpc.GenericServerStream[RepoList, RepoMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Importer_PullServer = grpc.ServerStreamingServer[RepoMsg]

func _Importer_Zip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImporterServer).Zip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Importer_Zip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImporterServer).Zip(ctx, req.(*RepoList))
	}
	return interceptor(ctx, in, info, handler)
}

// Importer_ServiceDesc is the grpc.ServiceDesc for Importer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Importer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repo.Importer",
	HandlerType: (*ImporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Zip",
			Handler:    _Importer_Zip_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _Importer_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Clone",
			Handler:       _Importer_Clone_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Where",
			Handler:       _Importer_Where_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Pull",
			Handler:       _Importer_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "repo.proto",
}
