// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: subcommands.proto

package genpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubCommandReq is the generic input for every SubCommands RPC: it identifies
// the repo to operate inside and supplies extra positional/flag args that are
// appended verbatim after the subcommand name. RPCs may apply a sensible
// happy-path default when args is empty (e.g. Add → ".", Commit → -m commit).
type SubCommandReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repo                  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCommandReq) Reset() {
	*x = SubCommandReq{}
	mi := &file_subcommands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCommandReq) ProtoMessage() {}

func (x *SubCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_subcommands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCommandReq.ProtoReflect.Descriptor instead.
func (*SubCommandReq) Descriptor() ([]byte, []int) {
	return file_subcommands_proto_rawDescGZIP(), []int{0}
}

func (x *SubCommandReq) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *SubCommandReq) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_subcommands_proto protoreflect.FileDescriptor

const file_subcommands_proto_rawDesc = "" +
	"\n" +
	"\x11subcommands.proto\x12\vsubcommands\x1a\n" +
	"repo.proto\x1a\x10subcommand.proto\"C\n" +
	"\rSubCommandReq\x12\x1e\n" +
	"\x04repo\x18\x01 \x01(\v2\n" +
	".repo.RepoR\x04repo\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args2\x80\x0f\n" +
	"\vSubCommands\x121\n" +
	"\aExecute\x12\x17.subcommands.Subcommand\x1a\r.repo.RepoMsg\x120\n" +
	"\x03Add\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x124\n" +
	"\aArchive\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x125\n" +
	"\bBackfill\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Bisect\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Branch\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Bundle\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x125\n" +
	"\bCheckout\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x127\n" +
	"\n" +
	"CherryPick\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x122\n" +
	"\x05Clean\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Commit\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x125\n" +
	"\bDescribe\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x121\n" +
	"\x04Diff\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x12/\n" +
	"\x02Gc\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x121\n" +
	"\x04Init\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x120\n" +
	"\x03Log\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x128\n" +
	"\vMaintenance\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x122\n" +
	"\x05Merge\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x12/\n" +
	"\x02Mv\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x122\n" +
	"\x05Notes\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x121\n" +
	"\x04Push\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x126\n" +
	"\tRangeDiff\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Rebase\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x122\n" +
	"\x05Reset\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x124\n" +
	"\aRestore\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Revert\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x12/\n" +
	"\x02Rm\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x125\n" +
	"\bShortlog\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x121\n" +
	"\x04Show\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x12;\n" +
	"\x0eSparseCheckout\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x122\n" +
	"\x05Stash\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Status\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x126\n" +
	"\tSubmodule\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x123\n" +
	"\x06Switch\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x120\n" +
	"\x03Tag\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsg\x125\n" +
	"\bWorktree\x12\x1a.subcommands.SubCommandReq\x1a\r.repo.RepoMsgB)Z'github.com/accretional/proto-repo/genpbb\x06proto3"

var (
	file_subcommands_proto_rawDescOnce sync.Once
	file_subcommands_proto_rawDescData []byte
)

func file_subcommands_proto_rawDescGZIP() []byte {
	file_subcommands_proto_rawDescOnce.Do(func() {
		file_subcommands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subcommands_proto_rawDesc), len(file_subcommands_proto_rawDesc)))
	})
	return file_subcommands_proto_rawDescData
}

var file_subcommands_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_subcommands_proto_goTypes = []any{
	(*SubCommandReq)(nil), // 0: subcommands.SubCommandReq
	(*Repo)(nil),          // 1: repo.Repo
	(*Subcommand)(nil),    // 2: subcommands.Subcommand
	(*RepoMsg)(nil),       // 3: repo.RepoMsg
}
var file_subcommands_proto_depIdxs = []int32{
	1,  // 0: subcommands.SubCommandReq.repo:type_name -> repo.Repo
	2,  // 1: subcommands.SubCommands.Execute:input_type -> subcommands.Subcommand
	0,  // 2: subcommands.SubCommands.Add:input_type -> subcommands.SubCommandReq
	0,  // 3: subcommands.SubCommands.Archive:input_type -> subcommands.SubCommandReq
	0,  // 4: subcommands.SubCommands.Backfill:input_type -> subcommands.SubCommandReq
	0,  // 5: subcommands.SubCommands.Bisect:input_type -> subcommands.SubCommandReq
	0,  // 6: subcommands.SubCommands.Branch:input_type -> subcommands.SubCommandReq
	0,  // 7: subcommands.SubCommands.Bundle:input_type -> subcommands.SubCommandReq
	0,  // 8: subcommands.SubCommands.Checkout:input_type -> subcommands.SubCommandReq
	0,  // 9: subcommands.SubCommands.CherryPick:input_type -> subcommands.SubCommandReq
	0,  // 10: subcommands.SubCommands.Clean:input_type -> subcommands.SubCommandReq
	0,  // 11: subcommands.SubCommands.Commit:input_type -> subcommands.SubCommandReq
	0,  // 12: subcommands.SubCommands.Describe:input_type -> subcommands.SubCommandReq
	0,  // 13: subcommands.SubCommands.Diff:input_type -> subcommands.SubCommandReq
	0,  // 14: subcommands.SubCommands.Gc:input_type -> subcommands.SubCommandReq
	0,  // 15: subcommands.SubCommands.Init:input_type -> subcommands.SubCommandReq
	0,  // 16: subcommands.SubCommands.Log:input_type -> subcommands.SubCommandReq
	0,  // 17: subcommands.SubCommands.Maintenance:input_type -> subcommands.SubCommandReq
	0,  // 18: subcommands.SubCommands.Merge:input_type -> subcommands.SubCommandReq
	0,  // 19: subcommands.SubCommands.Mv:input_type -> subcommands.SubCommandReq
	0,  // 20: subcommands.SubCommands.Notes:input_type -> subcommands.SubCommandReq
	0,  // 21: subcommands.SubCommands.Push:input_type -> subcommands.SubCommandReq
	0,  // 22: subcommands.SubCommands.RangeDiff:input_type -> subcommands.SubCommandReq
	0,  // 23: subcommands.SubCommands.Rebase:input_type -> subcommands.SubCommandReq
	0,  // 24: subcommands.SubCommands.Reset:input_type -> subcommands.SubCommandReq
	0,  // 25: subcommands.SubCommands.Restore:input_type -> subcommands.SubCommandReq
	0,  // 26: subcommands.SubCommands.Revert:input_type -> subcommands.SubCommandReq
	0,  // 27: subcommands.SubCommands.Rm:input_type -> subcommands.SubCommandReq
	0,  // 28: subcommands.SubCommands.Shortlog:input_type -> subcommands.SubCommandReq
	0,  // 29: subcommands.SubCommands.Show:input_type -> subcommands.SubCommandReq
	0,  // 30: subcommands.SubCommands.SparseCheckout:input_type -> subcommands.SubCommandReq
	0,  // 31: subcommands.SubCommands.Stash:input_type -> subcommands.SubCommandReq
	0,  // 32: subcommands.SubCommands.Status:input_type -> subcommands.SubCommandReq
	0,  // 33: subcommands.SubCommands.Submodule:input_type -> subcommands.SubCommandReq
	0,  // 34: subcommands.SubCommands.Switch:input_type -> subcommands.SubCommandReq
	0,  // 35: subcommands.SubCommands.Tag:input_type -> subcommands.SubCommandReq
	0,  // 36: subcommands.SubCommands.Worktree:input_type -> subcommands.SubCommandReq
	3,  // 37: subcommands.SubCommands.Execute:output_type -> repo.RepoMsg
	3,  // 38: subcommands.SubCommands.Add:output_type -> repo.RepoMsg
	3,  // 39: subcommands.SubCommands.Archive:output_type -> repo.RepoMsg
	3,  // 40: subcommands.SubCommands.Backfill:output_type -> repo.RepoMsg
	3,  // 41: subcommands.SubCommands.Bisect:output_type -> repo.RepoMsg
	3,  // 42: subcommands.SubCommands.Branch:output_type -> repo.RepoMsg
	3,  // 43: subcommands.SubCommands.Bundle:output_type -> repo.RepoMsg
	3,  // 44: subcommands.SubCommands.Checkout:output_type -> repo.RepoMsg
	3,  // 45: subcommands.SubCommands.CherryPick:output_type -> repo.RepoMsg
	3,  // 46: subcommands.SubCommands.Clean:output_type -> repo.RepoMsg
	3,  // 47: subcommands.SubCommands.Commit:output_type -> repo.RepoMsg
	3,  // 48: subcommands.SubCommands.Describe:output_type -> repo.RepoMsg
	3,  // 49: subcommands.SubCommands.Diff:output_type -> repo.RepoMsg
	3,  // 50: subcommands.SubCommands.Gc:output_type -> repo.RepoMsg
	3,  // 51: subcommands.SubCommands.Init:output_type -> repo.RepoMsg
	3,  // 52: subcommands.SubCommands.Log:output_type -> repo.RepoMsg
	3,  // 53: subcommands.SubCommands.Maintenance:output_type -> repo.RepoMsg
	3,  // 54: subcommands.SubCommands.Merge:output_type -> repo.RepoMsg
	3,  // 55: subcommands.SubCommands.Mv:output_type -> repo.RepoMsg
	3,  // 56: subcommands.SubCommands.Notes:output_type -> repo.RepoMsg
	3,  // 57: subcommands.SubCommands.Push:output_type -> repo.RepoMsg
	3,  // 58: subcommands.SubCommands.RangeDiff:output_type -> repo.RepoMsg
	3,  // 59: subcommands.SubCommands.Rebase:output_type -> repo.RepoMsg
	3,  // 60: subcommands.SubCommands.Reset:output_type -> repo.RepoMsg
	3,  // 61: subcommands.SubCommands.Restore:output_type -> repo.RepoMsg
	3,  // 62: subcommands.SubCommands.Revert:output_type -> repo.RepoMsg
	3,  // 63: subcommands.SubCommands.Rm:output_type -> repo.RepoMsg
	3,  // 64: subcommands.SubCommands.Shortlog:output_type -> repo.RepoMsg
	3,  // 65: subcommands.SubCommands.Show:output_type -> repo.RepoMsg
	3,  // 66: subcommands.SubCommands.SparseCheckout:output_type -> repo.RepoMsg
	3,  // 67: subcommands.SubCommands.Stash:output_type -> repo.RepoMsg
	3,  // 68: subcommands.SubCommands.Status:output_type -> repo.RepoMsg
	3,  // 69: subcommands.SubCommands.Submodule:output_type -> repo.RepoMsg
	3,  // 70: subcommands.SubCommands.Switch:output_type -> repo.RepoMsg
	3,  // 71: subcommands.SubCommands.Tag:output_type -> repo.RepoMsg
	3,  // 72: subcommands.SubCommands.Worktree:output_type -> repo.RepoMsg
	37, // [37:73] is the sub-list for method output_type
	1,  // [1:37] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_subcommands_proto_init() }
func file_subcommands_proto_init() {
	if File_subcommands_proto != nil {
		return
	}
	file_repo_proto_init()
	file_subcommand_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subcommands_proto_rawDesc), len(file_subcommands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subcommands_proto_goTypes,
		DependencyIndexes: file_subcommands_proto_depIdxs,
		MessageInfos:      file_subcommands_proto_msgTypes,
	}.Build()
	File_subcommands_proto = out.File
	file_subcommands_proto_goTypes = nil
	file_subcommands_proto_depIdxs = nil
}
