// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: subcommands.proto

package genpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubCommands_Execute_FullMethodName        = "/subcommands.SubCommands/Execute"
	SubCommands_Add_FullMethodName            = "/subcommands.SubCommands/Add"
	SubCommands_Archive_FullMethodName        = "/subcommands.SubCommands/Archive"
	SubCommands_Backfill_FullMethodName       = "/subcommands.SubCommands/Backfill"
	SubCommands_Bisect_FullMethodName         = "/subcommands.SubCommands/Bisect"
	SubCommands_Branch_FullMethodName         = "/subcommands.SubCommands/Branch"
	SubCommands_Bundle_FullMethodName         = "/subcommands.SubCommands/Bundle"
	SubCommands_Checkout_FullMethodName       = "/subcommands.SubCommands/Checkout"
	SubCommands_CherryPick_FullMethodName     = "/subcommands.SubCommands/CherryPick"
	SubCommands_Clean_FullMethodName          = "/subcommands.SubCommands/Clean"
	SubCommands_Commit_FullMethodName         = "/subcommands.SubCommands/Commit"
	SubCommands_Describe_FullMethodName       = "/subcommands.SubCommands/Describe"
	SubCommands_Diff_FullMethodName           = "/subcommands.SubCommands/Diff"
	SubCommands_Gc_FullMethodName             = "/subcommands.SubCommands/Gc"
	SubCommands_Init_FullMethodName           = "/subcommands.SubCommands/Init"
	SubCommands_Log_FullMethodName            = "/subcommands.SubCommands/Log"
	SubCommands_Maintenance_FullMethodName    = "/subcommands.SubCommands/Maintenance"
	SubCommands_Merge_FullMethodName          = "/subcommands.SubCommands/Merge"
	SubCommands_Mv_FullMethodName             = "/subcommands.SubCommands/Mv"
	SubCommands_Notes_FullMethodName          = "/subcommands.SubCommands/Notes"
	SubCommands_Push_FullMethodName           = "/subcommands.SubCommands/Push"
	SubCommands_RangeDiff_FullMethodName      = "/subcommands.SubCommands/RangeDiff"
	SubCommands_Rebase_FullMethodName         = "/subcommands.SubCommands/Rebase"
	SubCommands_Reset_FullMethodName          = "/subcommands.SubCommands/Reset"
	SubCommands_Restore_FullMethodName        = "/subcommands.SubCommands/Restore"
	SubCommands_Revert_FullMethodName         = "/subcommands.SubCommands/Revert"
	SubCommands_Rm_FullMethodName             = "/subcommands.SubCommands/Rm"
	SubCommands_Shortlog_FullMethodName       = "/subcommands.SubCommands/Shortlog"
	SubCommands_Show_FullMethodName           = "/subcommands.SubCommands/Show"
	SubCommands_SparseCheckout_FullMethodName = "/subcommands.SubCommands/SparseCheckout"
	SubCommands_Stash_FullMethodName          = "/subcommands.SubCommands/Stash"
	SubCommands_Status_FullMethodName         = "/subcommands.SubCommands/Status"
	SubCommands_Submodule_FullMethodName      = "/subcommands.SubCommands/Submodule"
	SubCommands_Switch_FullMethodName         = "/subcommands.SubCommands/Switch"
	SubCommands_Tag_FullMethodName            = "/subcommands.SubCommands/Tag"
	SubCommands_Worktree_FullMethodName       = "/subcommands.SubCommands/Worktree"
)

// SubCommandsClient is the client API for SubCommands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubCommands wraps individual `git <subcommand>` invocations. Each RPC runs
// `git <subcommand> <args...>` inside the request's resolved repo path and
// returns a RepoMsg carrying captured stdout/stderr and any error string.
type SubCommandsClient interface {
	// Execute dispatches on the Subcommand wrapper's args oneof, building the
	// git argv from the typed fields. Equivalent to the per-subcommand RPCs
	// below but callers don't have to know the shell-style arg format.
	Execute(ctx context.Context, in *Subcommand, opts ...grpc.CallOption) (*RepoMsg, error)
	Add(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Archive(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Backfill(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Bisect(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Branch(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Bundle(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Checkout(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	CherryPick(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Clean(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Commit(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Describe(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Diff(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Gc(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Init(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Log(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Maintenance(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Merge(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Mv(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Notes(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Push(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	RangeDiff(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Rebase(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Reset(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Restore(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Revert(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Rm(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Shortlog(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Show(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	SparseCheckout(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Stash(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Status(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Submodule(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Switch(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Tag(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
	Worktree(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error)
}

type subCommandsClient struct {
	cc grpc.ClientConnInterface
}

func NewSubCommandsClient(cc grpc.ClientConnInterface) SubCommandsClient {
	return &subCommandsClient{cc}
}

func (c *subCommandsClient) Execute(ctx context.Context, in *Subcommand, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Add(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Archive(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Archive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Backfill(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Backfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Bisect(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Bisect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Branch(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Branch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Bundle(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Bundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Checkout(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Checkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) CherryPick(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_CherryPick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Clean(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Clean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Commit(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Describe(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Diff(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Gc(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Gc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Init(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Log(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Maintenance(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Maintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Merge(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Merge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Mv(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Mv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Notes(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Notes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Push(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) RangeDiff(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_RangeDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Rebase(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Rebase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Reset(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Restore(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Revert(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Revert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Rm(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Rm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Shortlog(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Shortlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Show(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Show_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) SparseCheckout(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_SparseCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Stash(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Stash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Status(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Submodule(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Submodule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Switch(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Switch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Tag(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Tag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subCommandsClient) Worktree(ctx context.Context, in *SubCommandReq, opts ...grpc.CallOption) (*RepoMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoMsg)
	err := c.cc.Invoke(ctx, SubCommands_Worktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubCommandsServer is the server API for SubCommands service.
// All implementations must embed UnimplementedSubCommandsServer
// for forward compatibility.
//
// SubCommands wraps individual `git <subcommand>` invocations. Each RPC runs
// `git <subcommand> <args...>` inside the request's resolved repo path and
// returns a RepoMsg carrying captured stdout/stderr and any error string.
type SubCommandsServer interface {
	// Execute dispatches on the Subcommand wrapper's args oneof, building the
	// git argv from the typed fields. Equivalent to the per-subcommand RPCs
	// below but callers don't have to know the shell-style arg format.
	Execute(context.Context, *Subcommand) (*RepoMsg, error)
	Add(context.Context, *SubCommandReq) (*RepoMsg, error)
	Archive(context.Context, *SubCommandReq) (*RepoMsg, error)
	Backfill(context.Context, *SubCommandReq) (*RepoMsg, error)
	Bisect(context.Context, *SubCommandReq) (*RepoMsg, error)
	Branch(context.Context, *SubCommandReq) (*RepoMsg, error)
	Bundle(context.Context, *SubCommandReq) (*RepoMsg, error)
	Checkout(context.Context, *SubCommandReq) (*RepoMsg, error)
	CherryPick(context.Context, *SubCommandReq) (*RepoMsg, error)
	Clean(context.Context, *SubCommandReq) (*RepoMsg, error)
	Commit(context.Context, *SubCommandReq) (*RepoMsg, error)
	Describe(context.Context, *SubCommandReq) (*RepoMsg, error)
	Diff(context.Context, *SubCommandReq) (*RepoMsg, error)
	Gc(context.Context, *SubCommandReq) (*RepoMsg, error)
	Init(context.Context, *SubCommandReq) (*RepoMsg, error)
	Log(context.Context, *SubCommandReq) (*RepoMsg, error)
	Maintenance(context.Context, *SubCommandReq) (*RepoMsg, error)
	Merge(context.Context, *SubCommandReq) (*RepoMsg, error)
	Mv(context.Context, *SubCommandReq) (*RepoMsg, error)
	Notes(context.Context, *SubCommandReq) (*RepoMsg, error)
	Push(context.Context, *SubCommandReq) (*RepoMsg, error)
	RangeDiff(context.Context, *SubCommandReq) (*RepoMsg, error)
	Rebase(context.Context, *SubCommandReq) (*RepoMsg, error)
	Reset(context.Context, *SubCommandReq) (*RepoMsg, error)
	Restore(context.Context, *SubCommandReq) (*RepoMsg, error)
	Revert(context.Context, *SubCommandReq) (*RepoMsg, error)
	Rm(context.Context, *SubCommandReq) (*RepoMsg, error)
	Shortlog(context.Context, *SubCommandReq) (*RepoMsg, error)
	Show(context.Context, *SubCommandReq) (*RepoMsg, error)
	SparseCheckout(context.Context, *SubCommandReq) (*RepoMsg, error)
	Stash(context.Context, *SubCommandReq) (*RepoMsg, error)
	Status(context.Context, *SubCommandReq) (*RepoMsg, error)
	Submodule(context.Context, *SubCommandReq) (*RepoMsg, error)
	Switch(context.Context, *SubCommandReq) (*RepoMsg, error)
	Tag(context.Context, *SubCommandReq) (*RepoMsg, error)
	Worktree(context.Context, *SubCommandReq) (*RepoMsg, error)
	mustEmbedUnimplementedSubCommandsServer()
}

// UnimplementedSubCommandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubCommandsServer struct{}

func (UnimplementedSubCommandsServer) Execute(context.Context, *Subcommand) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSubCommandsServer) Add(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedSubCommandsServer) Archive(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedSubCommandsServer) Backfill(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backfill not implemented")
}
func (UnimplementedSubCommandsServer) Bisect(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bisect not implemented")
}
func (UnimplementedSubCommandsServer) Branch(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Branch not implemented")
}
func (UnimplementedSubCommandsServer) Bundle(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bundle not implemented")
}
func (UnimplementedSubCommandsServer) Checkout(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}
func (UnimplementedSubCommandsServer) CherryPick(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CherryPick not implemented")
}
func (UnimplementedSubCommandsServer) Clean(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clean not implemented")
}
func (UnimplementedSubCommandsServer) Commit(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedSubCommandsServer) Describe(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedSubCommandsServer) Diff(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedSubCommandsServer) Gc(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gc not implemented")
}
func (UnimplementedSubCommandsServer) Init(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedSubCommandsServer) Log(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedSubCommandsServer) Maintenance(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Maintenance not implemented")
}
func (UnimplementedSubCommandsServer) Merge(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Merge not implemented")
}
func (UnimplementedSubCommandsServer) Mv(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mv not implemented")
}
func (UnimplementedSubCommandsServer) Notes(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notes not implemented")
}
func (UnimplementedSubCommandsServer) Push(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedSubCommandsServer) RangeDiff(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangeDiff not implemented")
}
func (UnimplementedSubCommandsServer) Rebase(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rebase not implemented")
}
func (UnimplementedSubCommandsServer) Reset(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedSubCommandsServer) Restore(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedSubCommandsServer) Revert(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revert not implemented")
}
func (UnimplementedSubCommandsServer) Rm(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rm not implemented")
}
func (UnimplementedSubCommandsServer) Shortlog(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shortlog not implemented")
}
func (UnimplementedSubCommandsServer) Show(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedSubCommandsServer) SparseCheckout(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SparseCheckout not implemented")
}
func (UnimplementedSubCommandsServer) Stash(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stash not implemented")
}
func (UnimplementedSubCommandsServer) Status(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSubCommandsServer) Submodule(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submodule not implemented")
}
func (UnimplementedSubCommandsServer) Switch(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Switch not implemented")
}
func (UnimplementedSubCommandsServer) Tag(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tag not implemented")
}
func (UnimplementedSubCommandsServer) Worktree(context.Context, *SubCommandReq) (*RepoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Worktree not implemented")
}
func (UnimplementedSubCommandsServer) mustEmbedUnimplementedSubCommandsServer() {}
func (UnimplementedSubCommandsServer) testEmbeddedByValue()                     {}

// UnsafeSubCommandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubCommandsServer will
// result in compilation errors.
type UnsafeSubCommandsServer interface {
	mustEmbedUnimplementedSubCommandsServer()
}

func RegisterSubCommandsServer(s grpc.ServiceRegistrar, srv SubCommandsServer) {
	// If the following call pancis, it indicates UnimplementedSubCommandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubCommands_ServiceDesc, srv)
}

func _SubCommands_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subcommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Execute(ctx, req.(*Subcommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Add(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Archive(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Backfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Backfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Backfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Backfill(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Bisect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Bisect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Bisect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Bisect(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Branch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Branch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Branch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Branch(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Bundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Bundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Bundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Bundle(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Checkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Checkout(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_CherryPick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).CherryPick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_CherryPick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).CherryPick(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Clean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Clean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Clean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Clean(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Commit(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Describe(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Diff(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Gc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Gc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Gc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Gc(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Init(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Log(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Maintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Maintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Maintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Maintenance(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Merge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Merge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Merge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Merge(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Mv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Mv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Mv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Mv(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Notes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Notes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Notes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Notes(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Push(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_RangeDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).RangeDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_RangeDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).RangeDiff(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Rebase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Rebase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Rebase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Rebase(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Reset(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Restore(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Revert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Revert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Revert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Revert(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Rm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Rm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Rm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Rm(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Shortlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Shortlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Shortlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Shortlog(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Show(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_SparseCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).SparseCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_SparseCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).SparseCheckout(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Stash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Stash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Stash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Stash(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Status(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Submodule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Submodule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Submodule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Submodule(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Switch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Switch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Switch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Switch(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Tag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Tag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Tag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Tag(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubCommands_Worktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubCommandsServer).Worktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubCommands_Worktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubCommandsServer).Worktree(ctx, req.(*SubCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SubCommands_ServiceDesc is the grpc.ServiceDesc for SubCommands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubCommands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subcommands.SubCommands",
	HandlerType: (*SubCommandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SubCommands_Execute_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _SubCommands_Add_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _SubCommands_Archive_Handler,
		},
		{
			MethodName: "Backfill",
			Handler:    _SubCommands_Backfill_Handler,
		},
		{
			MethodName: "Bisect",
			Handler:    _SubCommands_Bisect_Handler,
		},
		{
			MethodName: "Branch",
			Handler:    _SubCommands_Branch_Handler,
		},
		{
			MethodName: "Bundle",
			Handler:    _SubCommands_Bundle_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _SubCommands_Checkout_Handler,
		},
		{
			MethodName: "CherryPick",
			Handler:    _SubCommands_CherryPick_Handler,
		},
		{
			MethodName: "Clean",
			Handler:    _SubCommands_Clean_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _SubCommands_Commit_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _SubCommands_Describe_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _SubCommands_Diff_Handler,
		},
		{
			MethodName: "Gc",
			Handler:    _SubCommands_Gc_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _SubCommands_Init_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _SubCommands_Log_Handler,
		},
		{
			MethodName: "Maintenance",
			Handler:    _SubCommands_Maintenance_Handler,
		},
		{
			MethodName: "Merge",
			Handler:    _SubCommands_Merge_Handler,
		},
		{
			MethodName: "Mv",
			Handler:    _SubCommands_Mv_Handler,
		},
		{
			MethodName: "Notes",
			Handler:    _SubCommands_Notes_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _SubCommands_Push_Handler,
		},
		{
			MethodName: "RangeDiff",
			Handler:    _SubCommands_RangeDiff_Handler,
		},
		{
			MethodName: "Rebase",
			Handler:    _SubCommands_Rebase_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _SubCommands_Reset_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _SubCommands_Restore_Handler,
		},
		{
			MethodName: "Revert",
			Handler:    _SubCommands_Revert_Handler,
		},
		{
			MethodName: "Rm",
			Handler:    _SubCommands_Rm_Handler,
		},
		{
			MethodName: "Shortlog",
			Handler:    _SubCommands_Shortlog_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _SubCommands_Show_Handler,
		},
		{
			MethodName: "SparseCheckout",
			Handler:    _SubCommands_SparseCheckout_Handler,
		},
		{
			MethodName: "Stash",
			Handler:    _SubCommands_Stash_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SubCommands_Status_Handler,
		},
		{
			MethodName: "Submodule",
			Handler:    _SubCommands_Submodule_Handler,
		},
		{
			MethodName: "Switch",
			Handler:    _SubCommands_Switch_Handler,
		},
		{
			MethodName: "Tag",
			Handler:    _SubCommands_Tag_Handler,
		},
		{
			MethodName: "Worktree",
			Handler:    _SubCommands_Worktree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subcommands.proto",
}
